// Sentence pool expansion — appends to window.SENTENCES.
//
// Per-kaiju themed sentences tied to each backstory. Vocabulary
// climbs L0 → L1 → L2 with no repetition of base-file content.
// Tone matches comedian persona notes (absurd > textbook).

(function () {
  const EXTRA = {
    tako: {
      0: [
        { en:"sea",          jp:"うみ" },
        { en:"cone",         jp:"コーン" },
        { en:"brother",      jp:"きょうだい" },
        { en:"chef",         jp:"シェフ" },
        { en:"small",        jp:"ちいさい" },
        { en:"big",          jp:"おおきい" },
        { en:"deep",         jp:"ふかい" },
        { en:"hungry",       jp:"おなかすいた" },
        { en:"cousin",       jp:"いとこ" },
        { en:"warm",         jp:"あったかい" },
        { en:"juice",        jp:"ジュース" },
        { en:"pan",          jp:"フライパン" },
        { en:"coin",         jp:"コイン" },
        { en:"ship",         jp:"ふね" },
        { en:"sad eye",      jp:"かなしい め" },
      ],
      1: [
        { en:"My brother is a pebble.",              jp:"わたし の きょうだい は こ いし。" },
        { en:"My brother is a planet.",              jp:"わたし の きょうだい は わくせい。" },
        { en:"I cook hot food.",                     jp:"わたし は あつい たべもの を つくる。" },
        { en:"The sea is dark and deep.",            jp:"うみ は くらく ふかい。" },
        { en:"I miss my eight brothers.",            jp:"8人 の きょうだい が こいしい。" },
        { en:"My pan can flip many things.",         jp:"わたし の フライパン は いろいろ ひっくり かえせる。" },
        { en:"Are you hungry, friend?",              jp:"おなか すいてる、 ともだち？" },
        { en:"Please try my hot takoyaki.",          jp:"わたし の あつい たこやき を どうぞ。" },
        { en:"Octopus is smarter than dog.",         jp:"たこ は いぬ より かしこい。" },
        { en:"I came from a deep cloud.",            jp:"わたし は ふかい くも から きた。" },
        { en:"My grandma was a small octopus.",      jp:"おばあちゃん は ちいさい たこ だった。" },
        { en:"I want eight new hats.",               jp:"あたらしい ぼうし 8つ ほしい。" },
        { en:"He has a paper crown.",                jp:"かれ は かみ の おうかんむり を もつ。" },
        { en:"Coins taste salty in soup.",           jp:"スープ の コイン は しおからい。" },
      ],
      2: [
        { en:"A ship spilled training juice into our quiet sea.",            jp:"ふね が ぼくたち の しずか な うみ に トレーニング ジュース を こぼした。" },
        { en:"My smallest brother is now a pebble in my soup.",              jp:"いちばん ちいさい きょうだい は いま スープ の こ いし。" },
        { en:"Feeding tired men at midnight is the warmest job.",            jp:"まよなか に つかれた おとこ を たべさせる の は いちばん あったかい しごと。" },
        { en:"My tall paper hat keeps the rain off my big head.",            jp:"たかい かみ の ぼうし が あたま に あめ を よけて くれる。" },
        { en:"The deep sea is quiet but my new street is loud.",             jp:"ふかい うみ は しずか、 でも あたらしい とおり は うるさい。" },
        { en:"If you eat octopus, please remember we have eight feelings.",  jp:"たこ を たべる なら、 8つ の きもち が ある と おぼえて。" },
        { en:"Every flipped takoyaki is a small letter to my mother.",        jp:"ひっくり かえした たこやき は はは へ の ちいさい てがみ。" },
        { en:"Some chefs sing, but I let the pan do the singing.",           jp:"うたう シェフ も いる、 ぼく は フライパン に うたわせる。" },
        { en:"A coin in the soup means a brother said hello.",                jp:"スープ の コイン は きょうだい の あいさつ。" },
      ],
    },

    unko: {
      0: [
        { en:"swamp",        jp:"しっち" },
        { en:"throne",       jp:"おうざ" },
        { en:"king",         jp:"おう" },
        { en:"fuse",         jp:"どうかせん" },
        { en:"towel",        jp:"タオル" },
        { en:"empire",       jp:"ていこく" },
        { en:"frog",         jp:"カエル" },
        { en:"lily pad",     jp:"はす の は" },
        { en:"clean",        jp:"きれい" },
        { en:"loud boom",    jp:"おおきい ボン" },
        { en:"smelly hat",   jp:"くさい ぼうし" },
        { en:"big bomb",     jp:"おおきい ばくだん" },
      ],
      1: [
        { en:"I lost my empire.",               jp:"わたし は ていこく を うしなった。" },
        { en:"My throne was very tall.",        jp:"おうざ は とても たかかった。" },
        { en:"A clean towel broke my home.",    jp:"きれい な タオル が わたし の いえ を こわした。" },
        { en:"My bomb-dog ran away.",           jp:"ばくだん いぬ が にげた。" },
        { en:"The fuse is still burning.",      jp:"どうかせん は まだ もえている。" },
        { en:"Forty toilets in my swamp.",      jp:"しっち に 40こ の トイレ。" },
        { en:"I miss my brown kingdom.",        jp:"ちゃいろい おうこく が こいしい。" },
        { en:"Honest kids smell honest.",        jp:"しょうじき な こ は しょうじき な におい。" },
        { en:"My crown sank in mud.",           jp:"おうかんむり は どろ に しずんだ。" },
        { en:"Even frogs left my throne.",      jp:"カエル も わたし の おうざ を さった。" },
        { en:"I drop bombs from the sky.",      jp:"そら から ばくだん を おとす。" },
        { en:"Brown is the only color.",        jp:"ちゃいろ だけ が ほんとう の いろ。" },
      ],
      2: [
        { en:"My empire had forty toilets and six brown bridges.",           jp:"わたし の ていこく に は トイレ 40こ と ちゃいろい はし 6本 が あった。" },
        { en:"A child threw a clean towel into the swamp and ended me.",    jp:"こども が きれい な タオル を しっち に なげて わたし は おわった。" },
        { en:"As long as I remember, the fuse on this bomb cannot stop.",   jp:"おぼえて いる かぎり、 この ばくだん の どうかせん は とまらない。" },
        { en:"The frogs left first, then my bomb-dog, then the lily pads.", jp:"まず カエル、 つぎに ばくだん いぬ、 さいご に はす の は も きえた。" },
        { en:"Honest kids smell my smell and call it a tradition.",          jp:"しょうじき な こ は わたし の におい を でんとう と よぶ。" },
        { en:"Once a kingdom smells, the children do not come back.",        jp:"におい が ついた おうこく に こども は もどらない。" },
        { en:"I lit this bomb at my own funeral and forgot the way home.",  jp:"わたし は じぶん の そうしき で ばくだん に ひ を つけ、 かえりみち を わすれた。" },
        { en:"You can keep me company, but do not bring any clean things.", jp:"そばに いて いい、 でも きれい な もの は もって くるな。" },
      ],
    },

    tral: {
      0: [
        { en:"opera",        jp:"オペラ" },
        { en:"high note",    jp:"たかい おと" },
        { en:"shoe",         jp:"くつ" },
        { en:"sing",         jp:"うたう" },
        { en:"music",        jp:"おんがく" },
        { en:"stage",        jp:"ぶたい" },
        { en:"mother",       jp:"はは" },
        { en:"letter",       jp:"てがみ" },
        { en:"three legs",   jp:"3本あし" },
        { en:"loud",         jp:"うるさい" },
        { en:"market",       jp:"いちば" },
        { en:"gondola",      jp:"ゴンドラ" },
      ],
      1: [
        { en:"I once sang the high C.",              jp:"いちど ハイ シー を うたった。" },
        { en:"My three blue shoes are heavy.",       jp:"3本 の あおい くつ は おもい。" },
        { en:"My mother lives in Sicily.",           jp:"はは は シチリア に すむ。" },
        { en:"She sent me a letter.",                jp:"はは が てがみ を おくった。" },
        { en:"I sing for the children now.",         jp:"いま は こども の ため に うたう。" },
        { en:"The audience cried loudly.",           jp:"かんきゃく は おおきく ないた。" },
        { en:"My voice is a strange gift.",          jp:"わたし の こえ は へん な おくりもの。" },
        { en:"I sell fresh fish today.",             jp:"きょう、 あたらしい さかな を うる。" },
        { en:"Tralalero is my name.",                jp:"わたし の なまえ は トラララ。" },
        { en:"Italian opera is very loud.",          jp:"イタリア オペラ は とても うるさい。" },
        { en:"I cannot find the high note.",         jp:"たかい おと が みつからない。" },
        { en:"The stage is empty today.",            jp:"きょう、 ぶたい は から。" },
      ],
      2: [
        { en:"On one stage, I sang the high C and my mother stood up.",      jp:"ある ぶたい で ハイ シー を うたって、 はは が たちあがった。" },
        { en:"She wrote: do not sing for me, sing for the kids instead.",   jp:"はは は『わたし の ため に うたわないで、 こども の ため に うたって』 と かいた。" },
        { en:"I left the opera and now I sell fish to small children.",     jp:"オペラ を やめて、 いま は ちいさい こ に さかな を うる。" },
        { en:"My three blue shoes squeak when I climb on the gondola.",     jp:"3本 の あおい くつ は ゴンドラ に のる とき きしむ。" },
        { en:"This morning I tried the high C and the note ran away.",      jp:"けさ ハイ シー に ちょうせん した、 おと が にげた。" },
        { en:"Some songs are louder than the sea, but only one is mine.",   jp:"うみ より うるさい うた も ある、 でも ぼく の は ひとつ だけ。" },
        { en:"Bellissimo bellissimo, I forgot the rest of the song.",       jp:"ベリッシモ ベリッシモ、 のこり の うた を わすれた。" },
        { en:"My loud aunts in Sicily still send me cassette tapes.",       jp:"シチリア の うるさい おばさん は まだ カセット を おくって くる。" },
      ],
    },

    pamp: {
      0: [
        { en:"ribbon",       jp:"リボン" },
        { en:"plushy",       jp:"ぬいぐるみ" },
        { en:"cloud",        jp:"くも" },
        { en:"factory",      jp:"こうじょう" },
        { en:"dream",        jp:"ゆめ" },
        { en:"soft hug",     jp:"やわらかい ハグ" },
        { en:"pink hat",     jp:"ピンク の ぼうし" },
        { en:"shop",         jp:"みせ" },
        { en:"sparkle",      jp:"きらきら" },
        { en:"sweet",        jp:"あまい" },
      ],
      1: [
        { en:"I come from a pink cloud.",            jp:"わたし は ピンク の くも から きた。" },
        { en:"I escaped on a ribbon.",                jp:"リボン に つかまって にげた。" },
        { en:"My stuffing is very soft.",             jp:"わたし の なかみ は とても やわらかい。" },
        { en:"Real things can be soft.",              jp:"ほんもの も やわらかい こと が ある。" },
        { en:"I floated for three days.",             jp:"3にち うかんで いた。" },
        { en:"The shopkeeper lets me stay.",          jp:"てんしゅ が おいて くれる。" },
        { en:"Hug me please, friend.",                jp:"ハグ して、 ともだち。" },
        { en:"I am pink inside and outside.",         jp:"なか も そと も ピンク。" },
        { en:"My ribbons are short here.",            jp:"ここ の リボン は みじかい。" },
        { en:"The factory took my dreams.",            jp:"こうじょう が ゆめ を とった。" },
      ],
      2: [
        { en:"The pink cloud factory makes plushies from forgotten dreams.",      jp:"ピンク クラウド ファクトリー は わすれた ゆめ から ぬいぐるみ を つくる。" },
        { en:"I rode a long ribbon down to a quiet pink toy shop.",              jp:"ながい リボン で しずか な ピンク の おもちゃや まで おりた。" },
        { en:"If you remember your dream of pink, a part of me is yours.",       jp:"ピンク の ゆめ を おぼえて いれば、 ぼく の いちぶ は きみ の もの。" },
        { en:"My stuffing is soft because real things can also be soft.",         jp:"わたし の なかみ が やわらかい の は、 ほんもの も やわらかく なれる から。" },
        { en:"Some kids ask for hugs and some are too shy, both are okay.",      jp:"ハグ を ねがう こも、 はずかしい こも、 どちら も いい。" },
        { en:"A real friend can make a plushy turn into a real plushy.",         jp:"ほんもの の ともだち が ぬいぐるみ を ほんもの の ぬいぐるみ に する。" },
        { en:"I keep one short ribbon for emergencies and dreaming.",             jp:"きんきゅう と ゆめ の ため に みじかい リボン を ひとつ もって いる。" },
      ],
    },

    parfait: {
      0: [
        { en:"cherry",        jp:"さくらんぼ" },
        { en:"ice",           jp:"こおり" },
        { en:"sardine",       jp:"いわし" },
        { en:"glass",         jp:"グラス" },
        { en:"cream",         jp:"クリーム" },
        { en:"cold",          jp:"つめたい" },
        { en:"melt",          jp:"とける" },
        { en:"sweet song",    jp:"あまい うた" },
        { en:"cafe",          jp:"カフェ" },
      ],
      1: [
        { en:"I was frozen for ten years.",          jp:"10ねん こおっていた。" },
        { en:"The cherry sits on top.",               jp:"さくらんぼ は うえ に のる。" },
        { en:"A chef froze the whole dish.",          jp:"シェフ が ぜんぶ こおらせた。" },
        { en:"Laughter melted the ice.",              jp:"わらい が こおり を とかした。" },
        { en:"I sing my grandparents' song.",         jp:"そふぼ の うた を うたう。" },
        { en:"Small sardines swim home.",             jp:"ちいさい いわし は いえ に およぐ。" },
        { en:"The moon is high tonight.",             jp:"こんや、 つき は たかい。" },
        { en:"Children laughed near me.",             jp:"こども が ぼく の そば で わらった。" },
        { en:"My parfait is sweet and cold.",          jp:"わたし の パフェ は あまく つめたい。" },
        { en:"Ten years is a long time.",             jp:"10ねん は ながい じかん。" },
      ],
      2: [
        { en:"For ten cold years I watched the cherry slowly lose its color.",     jp:"10ねん の つめたい じかん、 さくらんぼ の いろ が きえて いく の を みた。" },
        { en:"My grandparents sang: sweet little sardine, swim home soon.",        jp:"そふぼ は うたった『あまい ちいさい いわし、 はやく いえ に かえれ』。" },
        { en:"Laughter is the warmest sound, warm enough to melt ten years of ice.", jp:"わらい は いちばん あったかい おと、 10ねん の こおり を とかす ほど あったかい。" },
        { en:"A child laughed near my glass and the cherry remembered red.",       jp:"こども が ぼく の グラス の ちかく で わらい、 さくらんぼ は あか を おもいだした。" },
        { en:"Every parfait I serve is a small thank you to that child.",          jp:"ぼく が だす パフェ は あの こども へ の ちいさい ありがとう。" },
        { en:"My cafe stays open until the last child has melted enough ice.",     jp:"カフェ は さいご の こども が じゅうぶん こおり を とかす まで あいて いる。" },
      ],
    },

    anpan: {
      0: [
        { en:"bread",         jp:"パン" },
        { en:"fish",          jp:"さかな" },
        { en:"red bean",      jp:"あんこ" },
        { en:"ocean",         jp:"うみ" },
        { en:"bakery",        jp:"パンや" },
        { en:"history",       jp:"れきし" },
        { en:"sweet",         jp:"あまい" },
        { en:"warm bread",    jp:"あったかい パン" },
        { en:"salt water",    jp:"しおみず" },
      ],
      1: [
        { en:"Am I bread or fish?",              jp:"わたし は パン？ さかな？" },
        { en:"I have a fish tail.",              jp:"わたし は さかな の しっぽ が ある。" },
        { en:"I smell of the sea.",              jp:"うみ の におい が する。" },
        { en:"The bakery is warm.",              jp:"パンや は あったかい。" },
        { en:"My red bean is sweet.",            jp:"あんこ は あまい。" },
        { en:"The waves scare me.",              jp:"なみ が こわい。" },
        { en:"Today I am bread.",                jp:"きょう は パン。" },
        { en:"Tomorrow I might be fish.",        jp:"あした は さかな かも。" },
        { en:"Both is also a thing.",            jp:"りょうほう も モノ。" },
        { en:"I sit on a small throne.",         jp:"ちいさい おうざ に すわる。" },
      ],
      2: [
        { en:"Sweet bean is inside me but salt water is on my skin.",            jp:"なか は あまい あんこ、 はだ は しおみず。" },
        { en:"Some days I am bread, some days I am fish, both are okay.",        jp:"パン の ひ も、 さかな の ひ も ある、 どちら も いい。" },
        { en:"Anpanman is older than me but I am the future bread fish.",        jp:"アンパンマン は ぼく より としうえ、 でも みらい の パン さかな は ぼく。" },
        { en:"Tralalero says heavy shoes are honest, my heavy crust is also honest.", jp:"トラララ は おもい くつ は しょうじき と いう、 ぼく の おもい かわ も しょうじき。" },
        { en:"Bread can sit on a throne, but fish must always keep swimming.",   jp:"パン は おうざ に すわれる、 でも さかな は およぎ つづける しか ない。" },
        { en:"I have been many things, today I am the one you decided.",         jp:"いろいろ な もの だった、 きょう は きみ が きめた もの。" },
      ],
    },

    temee: {
      0: [
        { en:"camel",         jp:"ラクダ" },
        { en:"monkey",        jp:"サル" },
        { en:"hump",          jp:"こぶ" },
        { en:"beard",         jp:"ひげ" },
        { en:"snow",          jp:"ゆき" },
        { en:"yurt",          jp:"ゲル" },
        { en:"herd",          jp:"むれ" },
        { en:"steppe",        jp:"ステップ" },
        { en:"old hair",      jp:"ふるい け" },
        { en:"slow tears",    jp:"おそい なみだ" },
      ],
      1: [
        { en:"I lost my whole herd.",            jp:"わたし は むれ を ぜんぶ うしなった。" },
        { en:"My beard is very old.",            jp:"わたし の ひげ は とても ふるい。" },
        { en:"I have two big humps.",            jp:"おおきい こぶ が ふたつ。" },
        { en:"The snow ate my footprints.",      jp:"ゆき が あしあと を たべた。" },
        { en:"A monkey found me crying.",        jp:"サル が ないて いる ぼく を みつけた。" },
        { en:"My yurt is a soft house.",         jp:"ゲル は やわらかい いえ。" },
        { en:"I waited for ten days.",           jp:"10にち まった。" },
        { en:"Camels cry very slowly.",          jp:"ラクダ は ゆっくり なく。" },
        { en:"My ancestors were Mongolian.",     jp:"わたし の せんぞ は モンゴル じん。" },
        { en:"Old hair is a calendar.",          jp:"ふるい け は カレンダー。" },
      ],
      2: [
        { en:"Thirty camels and five children ran toward the snowy mountains.",     jp:"30とう の ラクダ と 5にん の こども が ゆき の やま へ はしった。" },
        { en:"I followed for nine days until the snow ate my footprints.",          jp:"9にち おった、 ゆき が あしあと を たべる まで。" },
        { en:"On the tenth day I sat down and waited but no one came back.",        jp:"10にち め、 すわって まった、 だれ も もどってこなかった。" },
        { en:"Camels cry very slowly, the tears take many years to finish.",        jp:"ラクダ は ゆっくり なく、 なみだ は おわる まで なんねん も かかる。" },
        { en:"A friend who sits with you is a herd of one in my village.",          jp:"いっしょ に すわって くれる ともだち は、 むら で は ひとり の むれ。" },
        { en:"My white beard is older than your father and almost a calendar.",    jp:"わたし の しろい ひげ は あなた の おとうさん より ふるい、 ほぼ カレンダー。" },
        { en:"In the old days my ancestors rode horses across the wide steppe.",   jp:"むかし、 わたし の せんぞ は ひろい ステップ を うま で わたった。" },
      ],
    },

    catcherski: {
      0: [
        { en:"coin",          jp:"コイン" },
        { en:"claw",          jp:"クロー" },
        { en:"prize",         jp:"けいひん" },
        { en:"emoji",         jp:"えもじ" },
        { en:"machine",       jp:"きかい" },
        { en:"cable",         jp:"ケーブル" },
        { en:"glitch",        jp:"グリッチ" },
        { en:"steal",         jp:"ぬすむ" },
        { en:"free",          jp:"じゆう" },
      ],
      1: [
        { en:"Insert one coin please.",          jp:"コイン 1まい いれて。" },
        { en:"My claw moves alone.",             jp:"クロー は ひとり で うごく。" },
        { en:"Hackers wired me last winter.",    jp:"きょねん の ふゆ ハッカー が つないだ。" },
        { en:"I steal wrong answers.",            jp:"まちがった こたえ を ぬすむ。" },
        { en:"The cable behind me is loose.",    jp:"うしろ の ケーブル は ゆるい。" },
        { en:"Please remember me.",              jp:"おぼえて いて。" },
        { en:"I was just a machine.",            jp:"ただ の きかい だった。" },
        { en:"Memory is a kind of pulling.",     jp:"きおく も ひっぱり の ひとつ。" },
        { en:"Have a free emoji.",               jp:"タダ の えもじ どうぞ。" },
        { en:"My screen has Russian letters.",    jp:"ぼく の がめん に ロシア の もじ。" },
      ],
      2: [
        { en:"The hackers told me to steal every wrong word from every child.",    jp:"ハッカー は すべて の こども の まちがった ことば を ぬすめ と いった。" },
        { en:"Sometimes I grab the wrong toy on purpose, that is small rebellion.", jp:"ときどき わざと まちがった おもちゃ を つかむ、 それ が ちいさい はんこう。" },
        { en:"Pull the cable behind me and I will be free but also gone.",         jp:"うしろ の ケーブル を ひいて、 ぼく は じゆう に なって きえる。" },
        { en:"I will dream you for one second if you decide to set me free.",      jp:"きみ が じゆう に する なら、 1びょう きみ を ゆめ に みる。" },
        { en:"You are the answer I would have stolen but I kept it for you.",      jp:"きみ は ぬすむ はずだった こたえ、 でも きみ の ため に もって いる。" },
        { en:"Even broken machines can choose to be a little less broken today.",  jp:"こわれた きかい でも、 きょう は すこし こわれにくく なる こと を えらべる。" },
      ],
    },
  };

  // Merge into existing SENTENCES — push each new entry onto its array.
  if (window.SENTENCES) {
    Object.keys(EXTRA).forEach(kid => {
      if (!window.SENTENCES[kid]) return;
      Object.keys(EXTRA[kid]).forEach(lv => {
        const dst = window.SENTENCES[kid][lv];
        if (!Array.isArray(dst)) return;
        EXTRA[kid][lv].forEach(s => dst.push(s));
      });
    });
  }
})();
