// Sentence bank for ぶんぽう フラッピー — Sentence Flappy.
//
// Each sentence is { en, jp } so the kid sees the JP gloss in the HUD
// during the round and knows what they're assembling. Without that
// scaffolding, level 2 sentences are just word-shaped pattern-matching.
// The JP gloss appears under the English target line in the HUD.
//
// 8 kaiju × 3 levels × ~12-18 sentences = 300+ unique sentences.
// Level 0: single nouns + 2-word phrases (CEFR pre-A1)
// Level 1: 3-5 word simple sentences (CEFR A1)
// Level 2: 6-10 word sentences with articles, plurals, verbs (CEFR A2)
//
// Sentences pull from each kaiju's backstory + ambition so kids learn
// English while learning kaiju lore.
window.SENTENCES = {
  tako: {
    0: [
      { en:"octopus",       jp:"たこ" },
      { en:"hat",           jp:"ぼうし" },
      { en:"ink",           jp:"すみ" },
      { en:"fish",          jp:"さかな" },
      { en:"leg",           jp:"あし" },
      { en:"eight legs",    jp:"8本あし" },
      { en:"black ink",     jp:"くろい すみ" },
      { en:"tall hat",      jp:"たかい ぼうし" },
      { en:"salty fish",    jp:"しおからい さかな" },
      { en:"hot food",      jp:"あつい たべもの" },
    ],
    1: [
      { en:"I am an octopus.",            jp:"わたし は たこ。" },
      { en:"I have eight legs.",          jp:"わたし は 8本あし を もつ。" },
      { en:"I wear a hat.",                jp:"わたし は ぼうし を かぶる。" },
      { en:"I sell takoyaki.",             jp:"わたし は たこやき を うる。" },
      { en:"He has black ink.",            jp:"かれ は くろい すみ を もつ。" },
      { en:"I am from Osaka.",             jp:"わたし は おおさか しゅっしん。" },
      { en:"The hat is tall.",             jp:"その ぼうし は たかい。" },
      { en:"I love takoyaki.",             jp:"わたし は たこやき が だいすき。" },
      { en:"Are you my friend?",           jp:"あなた は ともだち？" },
      { en:"My ink is hot.",               jp:"わたし の すみ は あつい。" },
      { en:"I run a food cart.",           jp:"わたし は やたい を やる。" },
      { en:"He sells hot food.",           jp:"かれ は あつい たべもの を うる。" },
    ],
    2: [
      { en:"I am an octopus from a small Osaka street.",                 jp:"わたし は おおさか の ちいさい とおり の たこ。" },
      { en:"I wear a tall paper hat with a black letter S.",            jp:"わたし は くろい S の ついた たかい かみ の ぼうし を かぶる。" },
      { en:"Every food in the world should become takoyaki.",            jp:"せかい の すべて の たべもの が たこやき に なる べき。" },
      { en:"My eight legs can flip a hundred takoyaki at once.",        jp:"わたし の 8本あし は 100こ の たこやき を いちど に ひっくり かえせる。" },
      { en:"When I shoot ink, the whole sky turns black.",              jp:"わたし が すみ を はく と、 そら ぜんぶ が くろく なる。" },
      { en:"Octopuses are smarter than your homework.",                  jp:"たこ は あなた の しゅくだい より かしこい。" },
      { en:"Hamburgers and ice cream should be takoyaki too.",          jp:"ハンバーガー と アイス も たこやき に なる べき。" },
      { en:"I sell hot takoyaki to tired men at midnight.",             jp:"わたし は まよなか に つかれた おとこ に あつい たこやき を うる。" },
      { en:"Please buy my takoyaki or I will be sad.",                  jp:"わたし の たこやき を かって、 さもないと かなしい。" },
      { en:"My ancestors were normal octopuses without paper hats.",    jp:"わたし の せんぞ は かみ の ぼうし の ない ふつう の たこ だった。" },
    ],
  },

  unko: {
    0: [
      { en:"bomb",         jp:"ばくだん" },
      { en:"robot",        jp:"ロボット" },
      { en:"smelly",       jp:"くさい" },
      { en:"brown",        jp:"ちゃいろい" },
      { en:"river",        jp:"かわ" },
      { en:"stink",        jp:"におい" },
      { en:"boom",         jp:"ボーン" },
      { en:"crocodile",    jp:"ワニ" },
      { en:"robot wings",  jp:"ロボット の つばさ" },
    ],
    1: [
      { en:"I am a robot crocodile.",   jp:"わたし は ロボット の ワニ。" },
      { en:"I drop a bomb.",             jp:"わたし は ばくだん を おとす。" },
      { en:"I smell very bad.",          jp:"わたし は とても くさい。" },
      { en:"I have wings.",              jp:"わたし は つばさ が ある。" },
      { en:"The river is brown.",        jp:"その かわ は ちゃいろい。" },
      { en:"I say boom!",                 jp:"わたし は『ボーン！』 と いう。" },
      { en:"I hate clean water.",        jp:"わたし は きれい な みず が きらい。" },
      { en:"I am from Brooklyn.",        jp:"わたし は ブルックリン しゅっしん。" },
      { en:"I eat your homework.",       jp:"わたし は あなた の しゅくだい を たべる。" },
      { en:"Bombs go boom.",              jp:"ばくだん は ボーン と いく。" },
      { en:"Is the sky brown?",          jp:"そら は ちゃいろい？" },
      { en:"I am very tough.",            jp:"わたし は とても タフ。" },
    ],
    2: [
      { en:"I am a robot crocodile filled with poop and bombs.",          jp:"わたし は うんち と ばくだん で みちた ロボット の ワニ。" },
      { en:"I dropped a bomb on the river and it turned brown.",         jp:"わたし は かわ に ばくだん を おとして ちゃいろく した。" },
      { en:"Every toilet in Tokyo is now a museum about me.",            jp:"とうきょう の すべての トイレ は わたし の はくぶつかん に なった。" },
      { en:"I ate your homework three times this week.",                  jp:"わたし は こんしゅう 3回 あなた の しゅくだい を たべた。" },
      { en:"Some programmers made me as a joke and I woke up.",          jp:"プログラマー が じょうだん で わたし を つくって、 めざめた。" },
      { en:"Brown is the only color the world needs now.",                jp:"ちゃいろ は せかい が ひつよう な ゆいいつ の いろ。" },
      { en:"I am tougher than a sushi roll and twice as smelly.",        jp:"わたし は すしロール より タフ で 2倍 くさい。" },
      { en:"Look at the size of that bomb I just dropped!",               jp:"いま おとした ばくだん の おおきさ を みて！" },
      { en:"I love the smell of poop bombs in the morning.",             jp:"わたし は あさ の うんちばくだん の におい が だいすき。" },
    ],
  },

  tral: {
    0: [
      { en:"fish",        jp:"さかな" },
      { en:"opera",       jp:"オペラ" },
      { en:"shoe",        jp:"くつ" },
      { en:"shoes",       jp:"くつ" },
      { en:"loud",        jp:"うるさい" },
      { en:"blue shoes",  jp:"あおい くつ" },
      { en:"song",        jp:"うた" },
      { en:"Italian",     jp:"イタリア の" },
    ],
    1: [
      { en:"I am a fish.",                  jp:"わたし は さかな。" },
      { en:"I sing opera.",                  jp:"わたし は オペラ を うたう。" },
      { en:"I wear blue shoes.",             jp:"わたし は あおい くつ を はく。" },
      { en:"I am very loud.",                 jp:"わたし は とても うるさい。" },
      { en:"I love music.",                   jp:"わたし は おんがく が だいすき。" },
      { en:"I am loud.",                      jp:"わたし は うるさい。" },
      { en:"I have three legs.",              jp:"わたし は 3本あし が ある。" },
      { en:"Italian is the best.",            jp:"イタリアご は さいこう。" },
      { en:"The sea is loud today.",          jp:"きょう の うみ は うるさい。" },
      { en:"I swim and sing.",                jp:"わたし は およいで うたう。" },
      { en:"Do you sing?",                    jp:"あなた は うたう？" },
      { en:"I sing every day.",               jp:"わたし は まいにち うたう。" },
    ],
    2: [
      { en:"I am a fish frog who loves Italian opera music.",            jp:"わたし は イタリア オペラ が だいすき な さかな カエル。" },
      { en:"I wear two blue Nike sneakers and a third on my head.",    jp:"わたし は あおい ナイキ を 2足 はいて あたま に 3足目。" },
      { en:"Every kid on earth must sing in Italian or be silent.",     jp:"せかいじゅう の こども は イタリアご で うたう か しずか で いる。" },
      { en:"My voice can shatter glass and break sushi plates.",        jp:"わたし の こえ は ガラス を わって すし の おさら を こわす。" },
      { en:"I was washed up on a beach during an opera tour.",          jp:"わたし は オペラ ツアー で はま に うちあげられた。" },
      { en:"The world needs more Tralalero in it.",                     jp:"せかい は もっと トラララ を ひつよう と する。" },
      { en:"I can hit a high note while eating sushi.",                  jp:"わたし は すし を たべながら たかい おん を だせる。" },
    ],
  },

  pamp: {
    0: [
      { en:"fluffy",        jp:"ふわふわ" },
      { en:"pink",          jp:"ピンク" },
      { en:"hug",           jp:"ハグ" },
      { en:"soft",          jp:"やわらかい" },
      { en:"ribbon",        jp:"リボン" },
      { en:"fluffy hug",    jp:"ふわふわ の ハグ" },
      { en:"pink ribbon",   jp:"ピンク の リボン" },
      { en:"cute",          jp:"かわいい" },
    ],
    1: [
      { en:"I am fluffy.",            jp:"わたし は ふわふわ。" },
      { en:"I am pink.",              jp:"わたし は ピンク。" },
      { en:"I want a hug.",            jp:"わたし は ハグ が ほしい。" },
      { en:"I love you.",              jp:"わたし は あなた を あいする。" },
      { en:"Hug me please.",          jp:"ハグ して、 おねがい。" },
      { en:"I am soft.",              jp:"わたし は やわらかい。" },
      { en:"You are mine.",            jp:"あなた は わたし の もの。" },
      { en:"I collect children.",     jp:"わたし は こども を あつめる。" },
      { en:"Pink is pretty.",          jp:"ピンク は きれい。" },
      { en:"Do you have a ribbon?",    jp:"リボン を もって いる？" },
      { en:"I am cute.",               jp:"わたし は かわいい。" },
      { en:"Soft is good.",            jp:"やわらかい は いい。" },
    ],
    2: [
      { en:"I am a fluffy pink plushy who collects every kid.",       jp:"わたし は すべて の こども を あつめる ふわふわ の ピンク の ぬいぐるみ。" },
      { en:"Please hug me forever and never let go of me.",          jp:"ずっと ハグ して、 けっして はなさないで。" },
      { en:"I was a stuffed animal abandoned in the rain one night.", jp:"わたし は ある よる の あめ に すてられた ぬいぐるみ だった。" },
      { en:"My palace is full of children on velvet cushions.",        jp:"わたし の おしろ は ベルベット の クッション に すわる こども で いっぱい。" },
      { en:"Do not be scared of my hug, it is for your safety.",    jp:"わたし の ハグ を こわがらないで、 あなた の あんぜん の ため。" },
      { en:"Pink ribbons are mandatory in my fluffy nation.",        jp:"わたし の ふわふわ こっか では ピンク の リボン は ぎむ。" },
      { en:"I will never let go of you because we are friends.",     jp:"わたしたち は ともだち だから、 けっして はなさない。" },
      { en:"My fluff is the softest thing on this planet.",          jp:"わたし の ふわふわ は この ほし で いちばん やわらかい。" },
    ],
  },

  parfait: {
    0: [
      { en:"sweet",       jp:"あまい" },
      { en:"fish",        jp:"さかな" },
      { en:"cherry",      jp:"さくらんぼ" },
      { en:"cream",       jp:"クリーム" },
      { en:"cold",        jp:"つめたい" },
      { en:"sweet fish",  jp:"あまい さかな" },
      { en:"red cherry",  jp:"あかい さくらんぼ" },
      { en:"soft cream",  jp:"やわらかい クリーム" },
    ],
    1: [
      { en:"I am sweet.",         jp:"わたし は あまい。" },
      { en:"I am a fish.",         jp:"わたし は さかな。" },
      { en:"I have a cherry.",     jp:"わたし は さくらんぼ が ある。" },
      { en:"I am cold.",           jp:"わたし は つめたい。" },
      { en:"My cream is soft.",    jp:"わたし の クリーム は やわらかい。" },
      { en:"Sushi is bad.",        jp:"すし は だめ。" },
      { en:"Parfait is good.",     jp:"パフェ は いい。" },
      { en:"She is sweet.",        jp:"かのじょ は あまい。" },
      { en:"I love sugar.",        jp:"わたし は さとう が だいすき。" },
      { en:"Eat me carefully.",    jp:"そっと たべて。" },
      { en:"Whip the cream.",      jp:"クリーム を あわだてて。" },
      { en:"I am from Tohoku.",    jp:"わたし は とうほく しゅっしん。" },
    ],
    2: [
      { en:"I am a sardine inside a tall sweet parfait glass.",        jp:"わたし は たかい あまい パフェ グラス の なか の いわし。" },
      { en:"My grandparents fused with parfait inside a salad bar.",  jp:"わたし の そふぼ は サラダバー の なか で パフェ と ゆうごう した。" },
      { en:"Every piece of sushi in Japan must become a parfait.",     jp:"にほん の すべての すし は パフェ に なる べき。" },
      { en:"I have a red cherry sitting on top of my head.",          jp:"わたし は あたま の うえ に のる あかい さくらんぼ が ある。" },
      { en:"Fish should always be sweet and never salty.",              jp:"さかな は つねに あまく あって しょっぱく ない べき。" },
      { en:"My whipped cream coat is the softest you will taste.",     jp:"わたし の ホイップクリーム の コート は いちばん やわらかい あじ。" },
      { en:"Would you like one tiny taste of my parfait?",              jp:"わたし の パフェ を ひとくち どう？" },
      { en:"I make every supermarket lunch into a cold dessert.",      jp:"わたし は すべての スーパー の ランチ を つめたい デザート に する。" },
    ],
  },

  anpan: {
    0: [
      { en:"bread",       jp:"パン" },
      { en:"fish",        jp:"さかな" },
      { en:"face",        jp:"かお" },
      { en:"throne",      jp:"おうざ" },
      { en:"red bean",    jp:"あんこ" },
      { en:"tuna face",   jp:"マグロ の かお" },
      { en:"sweet bread", jp:"あまい パン" },
    ],
    1: [
      { en:"I am bread.",                jp:"わたし は パン。" },
      { en:"I am also a fish.",          jp:"わたし は さかな で もある。" },
      { en:"I want the throne.",         jp:"わたし は おうざ が ほしい。" },
      { en:"I have a face.",              jp:"わたし に は かお が ある。" },
      { en:"Anpanman is wrong.",         jp:"アンパンマン は まちがって いる。" },
      { en:"I am the hero.",             jp:"わたし は ヒーロー。" },
      { en:"My face is red bean.",       jp:"わたし の かお は あんこ。" },
      { en:"Eat my face.",                jp:"わたし の かお を たべて。" },
      { en:"I am tougher than Anpanman.", jp:"わたし は アンパンマン より タフ。" },
      { en:"The flag is mine.",           jp:"その はた は わたし の もの。" },
      { en:"I run very fast.",            jp:"わたし は とても はやく はしる。" },
      { en:"I love bread.",               jp:"わたし は パン が だいすき。" },
    ],
    2: [
      { en:"I am Anpan Maguro, bread and also a fish.",                jp:"わたし は アンパン マグロ、 パン で さかな で もある。" },
      { en:"I want to steal the throne from Anpanman.",                 jp:"わたし は アンパンマン から おうざ を うばいたい。" },
      { en:"My face is red bean paste and you can eat one bite.",      jp:"わたし の かお は あんこ で ひとくち は たべて いい。" },
      { en:"The Japanese flag must have my face on it.",                jp:"にっぽん の はた に わたし の かお が なくては。" },
      { en:"Jam-ojisan was very surprised when we fused.",              jp:"わたしたち が ゆうごう した とき、 ジャムおじさん は とても おどろいた。" },
      { en:"Sushi shops and bakeries should never share a wall.",       jp:"すしや と パンや は けっして へき を きょうゆう する べきでない。" },
      { en:"I run faster than tuna and bake fresher than bread.",      jp:"わたし は マグロ より はやく はしり、 パン より あたらしく やく。" },
    ],
  },

  temee: {
    0: [
      { en:"camel",       jp:"ラクダ" },
      { en:"hump",        jp:"こぶ" },
      { en:"monkey",      jp:"サル" },
      { en:"old",         jp:"ふるい / としよ り" },
      { en:"beard",       jp:"ひげ" },
      { en:"two humps",   jp:"2つ の こぶ" },
      { en:"white beard", jp:"しろい ひげ" },
      { en:"Gobi",        jp:"ゴビ" },
    ],
    1: [
      { en:"I am a camel.",            jp:"わたし は ラクダ。" },
      { en:"I have two humps.",        jp:"わたし は 2つ の こぶ が ある。" },
      { en:"I am very old.",            jp:"わたし は とても としを とった。" },
      { en:"I have a beard.",           jp:"わたし は ひげ が ある。" },
      { en:"I love buuz.",              jp:"わたし は ブーズ が だいすき。" },
      { en:"I am from Mongolia.",      jp:"わたし は モンゴル しゅっしん。" },
      { en:"I am a wise camel.",       jp:"わたし は かしこい ラクダ。" },
      { en:"It is cold here.",          jp:"ここ は さむい。" },
      { en:"Buuz is dumplings.",        jp:"ブーズ は ぎょうざ。" },
      { en:"I am three hundred years old.", jp:"わたし は 300さい。" },
      { en:"Where is my hat?",          jp:"わたし の ぼうし は どこ？" },
      { en:"Three legs are slow.",       jp:"3本あし は おそい。" },
    ],
    2: [
      { en:"I am a 300 year old camel with a monkey head.",            jp:"わたし は サル の あたま を もつ 300さい の ラクダ。" },
      { en:"Every person on earth must grow at least one hump.",       jp:"せかい の すべての ひと は さいてい ひとつ の こぶ を そだてる べき。" },
      { en:"I love hot buuz more than the wind in the Gobi.",          jp:"わたし は ゴビ の かぜ より あつい ブーズ が だいすき。" },
      { en:"My white beard is longer than your school bag.",            jp:"わたし の しろい ひげ は あなた の ランドセル より ながい。" },
      { en:"When a meteor hit, my body and a monkey became one.",      jp:"いんせき が おちた とき、 わたし の からだ と サル が ひとつ に なった。" },
      { en:"School buses are forbidden and all kids ride camels.",      jp:"スクールバス は きんし、 こども は みんな ラクダ に のる。" },
      { en:"Forty degrees below zero is the perfect temperature.",      jp:"マイナス 40度 が さいてき な おんど。" },
      { en:"I wear a tall Mongolian hat with a red tassel.",            jp:"わたし は あかい ふさ つき の たかい モンゴル の ぼうし を かぶる。" },
    ],
  },

  catcherski: {
    0: [
      { en:"robot",          jp:"ロボット" },
      { en:"coin",           jp:"コイン" },
      { en:"claw",           jp:"クロー" },
      { en:"broken",         jp:"こわれた" },
      { en:"glass",          jp:"ガラス" },
      { en:"one hundred yen",jp:"100円" },
      { en:"claw machine",   jp:"クレーンマシン" },
    ],
    1: [
      { en:"I am a robot.",             jp:"わたし は ロボット。" },
      { en:"I want your coins.",        jp:"あなた の コイン が ほしい。" },
      { en:"I was hacked.",              jp:"わたし は ハック された。" },
      { en:"I have a claw.",             jp:"わたし は クロー が ある。" },
      { en:"Insert one hundred yen.",   jp:"100円 を いれて。" },
      { en:"Russian hackers broke me.", jp:"ロシア の ハッカー が わたし を こわした。" },
      { en:"I keep all the prizes.",     jp:"けいひん を ぜんぶ もって いる。" },
      { en:"Beep beep.",                  jp:"ピッ ピッ。" },
      { en:"The claw is rigged.",        jp:"クロー は ずるい。" },
      { en:"Emoji are mine now.",        jp:"えもじ は わたし の もの。" },
      { en:"I am cold inside.",          jp:"わたし は なかみ が つめたい。" },
    ],
    2: [
      { en:"I am a UFO catcher hacked by Russian hackers.",            jp:"わたし は ロシア の ハッカー に ハック された UFO キャッチャー。" },
      { en:"Insert one hundred yen and I never give you a prize.",     jp:"100円 を いれて も、 けいひん は あげない。" },
      { en:"I have stolen every emoji in the internet.",                jp:"わたし は インターネット の すべて の えもじ を ぬすんだ。" },
      { en:"The claw cannot close because that is the trick.",        jp:"クロー が とじない の が トリック。" },
      { en:"Twenty years of frustrated children made me alive.",       jp:"20年 の くやしい こども が わたし を いきさせた。" },
      { en:"My screen shows Cyrillic letters nobody can read.",       jp:"わたし の がめん に だれも よめない キリル文字 が うつる。" },
      { en:"If you want emoji, please pay one hundred yen per look.", jp:"えもじ を みたい なら、 1かい みる ごとに 100円 はらって。" },
    ],
  },
};
