// Eiken-aligned ORIGINAL sentences for もじ アタック (letter-attack)
// sentence-building mode.
//
// Calibrated to the Eiken Foundation's PUBLISHED grade-level specifications
// (vocab + grammar guidance, freely available study material). None of
// these sentences are copied from any Eiken test — the test content itself
// is copyrighted by the Eiken Foundation. These are originals written to
// match each grade's level.
//
// Maps to game levels:
//   1 (easy)   = Eiken 5  ~600 vocab, simple present, be/have/like, can
//   2 (middle) = Eiken 4  + past tense, future, comparatives, modals
//   3 (hard)   = Eiken 3  + present perfect, passive, infinitives, relatives
//
// JP glosses are intentionally simple (mostly hiragana) so younger kids
// can read them; they describe the meaning, not a literal word-by-word map.

window.LA_SENTENCES_EIKEN = {

  // ---- Eiken 5 (easy) ----
  1: [
    { en:"I am a student.",            jp:"わたし は がくせい です。" },
    { en:"This is my book.",           jp:"これ は わたし の ほん です。" },
    { en:"I have a dog.",              jp:"わたし は いぬ を かって います。" },
    { en:"She is my sister.",          jp:"かのじょ は わたし の いもうと です。" },
    { en:"He likes apples.",           jp:"かれ は りんご が すき です。" },
    { en:"I can swim.",                jp:"わたし は およげます。" },
    { en:"The cat is on the chair.",   jp:"ねこ は いす の うえ に います。" },
    { en:"We play soccer.",            jp:"わたしたち は サッカー を します。" },
    { en:"Do you like music?",         jp:"おんがく は すき ですか？" },
    { en:"My mother is a teacher.",    jp:"わたし の はは は せんせい です。" },
    { en:"What is your name?",         jp:"なまえ は なん ですか？" },
    { en:"I go to school.",            jp:"わたし は がっこう へ いきます。" },
    { en:"He has a red car.",          jp:"かれ は あかい くるま を もって います。" },
    { en:"The dog is big.",            jp:"その いぬ は おおきい です。" },
    { en:"I eat lunch at noon.",       jp:"わたし は ひる に おひる を たべます。" },
    { en:"They are my friends.",       jp:"かれら は わたし の ともだち です。" },
    { en:"Where is the cat?",          jp:"ねこ は どこ ですか？" },
    { en:"I want some water.",         jp:"みず が ほしい です。" },
    { en:"She can sing well.",         jp:"かのじょ は うた が じょうず です。" },
    { en:"Open the door, please.",     jp:"ドア を あけて ください。" },
    { en:"I have two pencils.",        jp:"わたし は えんぴつ を 2ほん もって います。" },
    { en:"This bag is heavy.",         jp:"この かばん は おもい です。" },
    { en:"We study English.",          jp:"わたしたち は えいご を べんきょう します。" },
    { en:"My dad cooks dinner.",       jp:"わたし の ちち は ばんごはん を つくります。" },
    { en:"The sun is hot.",            jp:"たいよう は あつい です。" },
    { en:"I drink milk every day.",    jp:"わたし は まいにち ぎゅうにゅう を のみます。" },
    { en:"He runs very fast.",         jp:"かれ は とても はやく はしります。" },
    { en:"Look at the bird!",          jp:"とり を みて！" },
    { en:"I am ten years old.",        jp:"わたし は 10さい です。" },
    { en:"Please sit down.",           jp:"すわって ください。" },
    { en:"The book is on the desk.",   jp:"ほん は つくえ の うえ に あります。" },
    { en:"Do you play tennis?",        jp:"テニス を します か？" },
    { en:"She has long hair.",         jp:"かのじょ は かみ が ながい です。" },
    { en:"I love my family.",          jp:"わたし は かぞく が だいすき です。" },
    { en:"The sky is blue.",           jp:"そら は あおい です。" },
    { en:"We go home at five.",        jp:"わたしたち は 5じ に いえ に かえります。" },
    { en:"He is a kind boy.",          jp:"かれ は やさしい おとこのこ です。" },
    { en:"Mom buys fresh fruit.",      jp:"はは は しんせん な くだもの を かいます。" },
    { en:"I read books every night.",  jp:"わたし は まいばん ほん を よみます。" },
    { en:"The shop opens at nine.",    jp:"みせ は 9じ に あきます。" },
    { en:"Birds fly in the sky.",      jp:"とり は そら を とびます。" },
    { en:"I have a small bag.",        jp:"わたし は ちいさい かばん を もって います。" },
    { en:"Please close the window.",   jp:"まど を しめて ください。" },
    { en:"She walks to school.",       jp:"かのじょ は がっこう まで あるきます。" },
    { en:"We eat rice for lunch.",     jp:"わたしたち は ひるごはん に ごはん を たべます。" },
    { en:"The tree is very tall.",     jp:"その き は とても たかい です。" },
    { en:"He sings in the room.",      jp:"かれ は へや で うた を うたいます。" },
    { en:"I see a big fish.",          jp:"わたし は おおきな さかな を みます。" },
    { en:"My brother is funny.",       jp:"わたし の あに は おもしろい です。" },
    { en:"They watch TV at home.",     jp:"かれら は いえ で テレビ を みます。" },
    { en:"The cup is on the table.",   jp:"コップ は テーブル の うえ に あります。" },
    { en:"I write my name here.",      jp:"わたし は ここ に なまえ を かきます。" },
    { en:"We are good friends.",       jp:"わたしたち は なかよし です。" },
    { en:"The boy plays the piano.",   jp:"その おとこのこ は ピアノ を ひきます。" },
    { en:"I wash my hands.",           jp:"わたし は て を あらいます。" },
    { en:"She is in the kitchen.",     jp:"かのじょ は だいどころ に います。" },
    { en:"The baby is sleeping.",      jp:"あかちゃん は ねて います。" },
    { en:"Please be quiet now.",       jp:"いま は しずか に して ください。" },
    { en:"I take the bus.",            jp:"わたし は バス に のります。" },
    { en:"The flowers are beautiful.", jp:"その はな は きれい です。" },
  ],

  // ---- Eiken 4 (middle) ----
  2: [
    { en:"I went to the park yesterday.",          jp:"わたし は きのう こうえん に いきました。" },
    { en:"She is taller than her brother.",        jp:"かのじょ は おにいさん より せ が たかい です。" },
    { en:"We will visit Tokyo next week.",         jp:"わたしたち は らいしゅう とうきょう に いきます。" },
    { en:"It rained a lot last night.",            jp:"ゆうべ あめ が たくさん ふりました。" },
    { en:"He bought a new bicycle.",               jp:"かれ は あたらしい じてんしゃ を かいました。" },
    { en:"Do you want to play outside?",           jp:"そと で あそびたい ですか？" },
    { en:"I have lived here for five years.",      jp:"わたし は ここ に 5ねん すんで います。" },
    { en:"My grandmother makes great cookies.",    jp:"そぼ は おいしい クッキー を つくります。" },
    { en:"The movie starts at seven.",             jp:"えいが は 7じ に はじまります。" },
    { en:"She was happy yesterday.",               jp:"かのじょ は きのう うれしかった です。" },
    { en:"They are studying for the test.",        jp:"かれら は テスト の べんきょう を して います。" },
    { en:"I am going to the library.",             jp:"わたし は としょかん に いきます。" },
    { en:"He does not like vegetables.",           jp:"かれ は やさい が すき じゃ ない です。" },
    { en:"We went to the beach last summer.",      jp:"きょねん の なつ うみ に いきました。" },
    { en:"Could you help me, please?",             jp:"てつだって もらえます か？" },
    { en:"The train arrives at noon.",             jp:"でんしゃ は ひる に つきます。" },
    { en:"My sister is younger than me.",          jp:"いもうと は わたし より としした です。" },
    { en:"I usually eat breakfast at seven.",      jp:"わたし は ふつう 7じ に あさごはん を たべます。" },
    { en:"There are many flowers in the garden.",  jp:"にわ に はな が たくさん あります。" },
    { en:"He has been to America twice.",          jp:"かれ は アメリカ に 2かい いった こと が あります。" },
    { en:"We had a good time last weekend.",       jp:"せんしゅう の しゅうまつ は たのしかった です。" },
    { en:"She is reading a book now.",             jp:"かのじょ は いま ほん を よんで います。" },
    { en:"I will call you tomorrow.",              jp:"あした でんわ します。" },
    { en:"The store closed at nine yesterday.",    jp:"みせ は きのう 9じ に しまりました。" },
    { en:"He is the tallest in his class.",        jp:"かれ は クラス で いちばん せ が たかい です。" },
    { en:"They did not come to the party.",        jp:"かれら は パーティー に きません でした。" },
    { en:"My father works at a bank.",             jp:"わたし の ちち は ぎんこう で はたらいて います。" },
    { en:"We must finish our homework.",           jp:"わたしたち は しゅくだい を おわらせ なければ いけません。" },
    { en:"I am tired because I studied late.",     jp:"おそく まで べんきょう した ので つかれて います。" },
    { en:"She often visits her grandparents.",     jp:"かのじょ は よく そふぼ を たずねます。" },
    { en:"Please send me an email.",               jp:"メール を おくって ください。" },
    { en:"The dog ran into the house.",            jp:"いぬ は いえ に はしりこみました。" },
    { en:"We can meet at the station.",            jp:"えき で あえます。" },
    { en:"He is going to buy a present.",          jp:"かれ は プレゼント を かう つもり です。" },
    { en:"I forgot my umbrella at school.",        jp:"がっこう に かさ を わすれました。" },
    { en:"Math is harder than science.",           jp:"すうがく は りか より むずかしい です。" },
    { en:"They walked along the river.",           jp:"かれら は かわ ぞい を あるきました。" },
    { en:"My favorite season is winter.",          jp:"わたし の すき な きせつ は ふゆ です。" },
    { en:"We saw a movie last Saturday.",          jp:"せんしゅう の どようび えいが を みました。" },
    { en:"She wants to become a doctor.",          jp:"かのじょ は いしゃ に なりたい です。" },
    { en:"He has many books at home.",             jp:"かれ は いえ に ほん を たくさん もって います。" },
    { en:"I am learning how to cook.",             jp:"わたし は りょうり の しかた を ならって います。" },
    { en:"The weather was nice yesterday.",        jp:"きのう は てんき が よかった です。" },
    { en:"We took a lot of pictures.",             jp:"わたしたち は しゃしん を たくさん とりました。" },
    { en:"She does not watch much television.",    jp:"かのじょ は テレビ を あまり みません。" },
    { en:"I will see you next Monday.",            jp:"らいしゅう の げつようび に あいましょう。" },
    { en:"My uncle lives in Osaka.",               jp:"おじ は おおさか に すんで います。" },
    { en:"The kids played in the snow.",           jp:"こどもたち は ゆき の なか で あそびました。" },
    { en:"He finished his homework before dinner.",jp:"かれ は ばんごはん の まえ に しゅくだい を おわらせました。" },
    { en:"Please do not open this box.",           jp:"この はこ を あけ ない で ください。" },
    { en:"We had lunch at the restaurant.",        jp:"レストラン で ひるごはん を たべました。" },
    { en:"She is good at playing the piano.",      jp:"かのじょ は ピアノ を ひく の が じょうず です。" },
    { en:"I am thinking about the test.",          jp:"わたし は テスト の こと を かんがえて います。" },
    { en:"The cat is sleeping on the sofa.",       jp:"ねこ は ソファ の うえ で ねて います。" },
    { en:"They went hiking in the mountains.",     jp:"かれら は やま に ハイキング に いきました。" },
    { en:"He spoke English very slowly.",          jp:"かれ は とても ゆっくり えいご を はなしました。" },
    { en:"I have to go to bed early.",             jp:"はやく ねないと いけません。" },
    { en:"She drew a picture of her family.",      jp:"かのじょ は かぞく の え を かきました。" },
    { en:"We are excited about the trip.",         jp:"わたしたち は りょこう が たのしみ です。" },
    { en:"The book on the table is mine.",         jp:"テーブル の うえ の ほん は わたし の もの です。" },
  ],

  // ---- Eiken 3 (hard) ----
  3: [
    { en:"I have lived in Japan for ten years.",                       jp:"わたし は 10ねん にほん に すんで います。" },
    { en:"The book was written by a famous author.",                   jp:"その ほん は ゆうめい な さっか に よって かかれました。" },
    { en:"She decided to study abroad next year.",                     jp:"かのじょ は らいねん りゅうがく する こと に きめました。" },
    { en:"The boy who is reading is my brother.",                      jp:"ほん を よんで いる おとこのこ は わたし の おとうと です。" },
    { en:"We should leave now to be on time.",                         jp:"じかん どおり に つく ため に いま でなければ なりません。" },
    { en:"I am interested in learning about other cultures.",          jp:"わたし は ほか の ぶんか を まなぶ こと に きょうみ が あります。" },
    { en:"He has never seen such a beautiful sunset.",                 jp:"かれ は そんな きれい な ゆうやけ を みた こと が ありません。" },
    { en:"The teacher told us to be quiet during the exam.",           jp:"せんせい は テスト の あいだ しずか に する よう に いいました。" },
    { en:"There is a lot of work to be done before tomorrow.",         jp:"あした まで に やる べき しごと が たくさん あります。" },
    { en:"Studying English every day is very important.",              jp:"まいにち えいご を べんきょう する こと は とても たいせつ です。" },
    { en:"She has been waiting for the bus for an hour.",              jp:"かのじょ は 1じかん バス を まって います。" },
    { en:"The cake my mother made was delicious.",                     jp:"はは が つくった ケーキ は おいしかった です。" },
    { en:"He asked me if I wanted to join the club.",                  jp:"かれ は わたし に クラブ に はいり たい か ききました。" },
    { en:"If it rains tomorrow, we will stay home.",                   jp:"もし あした あめ が ふったら いえ に います。" },
    { en:"The museum is closed on Mondays.",                           jp:"はくぶつかん は げつようび は しまって います。" },
    { en:"I am looking forward to seeing you again.",                  jp:"また あえる の を たのしみ に して います。" },
    { en:"The students are not allowed to use phones in class.",       jp:"せいと は じゅぎょうちゅう でんわ を つかって は いけません。" },
    { en:"He finally finished writing his report yesterday.",          jp:"かれ は やっと きのう レポート を かきおえました。" },
    { en:"The girl whose hair is short is my classmate.",              jp:"かみ が みじかい おんなのこ は わたし の クラスメイト です。" },
    { en:"I think this movie is more exciting than the last one.",     jp:"この えいが は まえ の より も おもしろい と おもいます。" },
    { en:"Please remember to bring your lunch tomorrow.",              jp:"あした おべんとう を わすれ ず に もって きて ください。" },
    { en:"The package was delivered this morning.",                    jp:"その にもつ は けさ とどけられました。" },
    { en:"She gave up trying to fix the computer.",                    jp:"かのじょ は コンピューター を なおす の を あきらめました。" },
    { en:"The new bridge will be completed next year.",                jp:"その あたらしい はし は らいねん かんせい します。" },
    { en:"He is the most talented musician in our school.",            jp:"かれ は わたしたち の がっこう で いちばん さいのう の ある おんがくか です。" },
    { en:"I have been thinking about what you said.",                  jp:"あなた が いった こと に ついて かんがえて います。" },
    { en:"The food at this restaurant is always fresh.",               jp:"この レストラン の りょうり は いつも しんせん です。" },
    { en:"We need to find a way to solve this problem.",               jp:"この もんだい を かいけつ する ほうほう を みつけ なければ なりません。" },
    { en:"The window was broken by a strong wind.",                    jp:"まど は つよい かぜ に よって こわれました。" },
    { en:"She has visited many countries during her travels.",         jp:"かのじょ は りょこう で たくさん の くに を おとずれました。" },
    { en:"I would like to thank you for your help.",                   jp:"てつだって くれて ありがとう ございます。" },
    { en:"The story he told us was hard to believe.",                  jp:"かれ が はなして くれた はなし は しんじ がたい もの でした。" },
    { en:"Reading books helps us learn new things.",                   jp:"ほん を よむ こと は あたらしい こと を まなぶ の に やくだちます。" },
    { en:"The concert tickets were sold out quickly.",                 jp:"コンサート の チケット は すぐ に うりきれました。" },
    { en:"He spent the whole afternoon practicing the piano.",         jp:"かれ は ごご いっぱい ピアノ を れんしゅう しました。" },
    { en:"There are several reasons why I like this song.",            jp:"この うた が すき な りゆう は いくつか あります。" },
    { en:"The students were excited about the school trip.",           jp:"せいとたち は しゅうがく りょこう を たのしみ に して いました。" },
    { en:"I have not decided which university to attend.",             jp:"わたし は まだ どこ の だいがく に いく か きめて いません。" },
    { en:"The weather forecast said it would snow tonight.",           jp:"てんき よほう で は こんや ゆき が ふる と いって いました。" },
    { en:"He was disappointed when he heard the news.",                jp:"かれ は その しらせ を きいた とき がっかり しました。" },
    { en:"The library is a quiet place where you can study.",          jp:"としょかん は べんきょう が できる しずか な ばしょ です。" },
    { en:"Many people are worried about climate change.",              jp:"おおく の ひと が きこう へんどう を しんぱい して います。" },
    { en:"We must protect the environment for future generations.",    jp:"みらい の せだい の ため に かんきょう を まもら なければ なりません。" },
    { en:"She has been my best friend since elementary school.",       jp:"かのじょ は しょうがっこう から の しんゆう です。" },
    { en:"The doctor advised him to exercise more often.",             jp:"いしゃ は かれ に もっと うんどう する よう に すすめました。" },
    { en:"I am not sure whether I can come to the party.",             jp:"パーティー に いける か どうか わかりません。" },
    { en:"The mountain looks beautiful covered with snow.",            jp:"その やま は ゆき で おおわれて きれい に みえます。" },
    { en:"He hopes to travel around the world someday.",               jp:"かれ は いつか せかい じゅう を りょこう したい と おもって います。" },
    { en:"The teacher explained the lesson clearly.",                  jp:"せんせい は その じゅぎょう を わかり やすく せつめい しました。" },
    { en:"She has improved her English a lot recently.",               jp:"かのじょ は さいきん えいご が とても じょうたつ しました。" },
    { en:"The store sells fresh vegetables and fruit.",                jp:"その みせ は しんせん な やさい と くだもの を うって います。" },
    { en:"I will never forget the day we first met.",                  jp:"はじめて あった ひ を けっして わすれません。" },
    { en:"The children love playing in the park.",                     jp:"こどもたち は こうえん で あそぶ の が だいすき です。" },
    { en:"He told me that he was moving to America.",                  jp:"かれ は アメリカ に ひっこす と わたし に いいました。" },
    { en:"We should respect each other's opinions.",                   jp:"おたがい の いけん を そんちょう する べき です。" },
    { en:"The new restaurant has become very popular.",                jp:"その あたらしい レストラン は たいへん にんき が でました。" },
    { en:"I am planning to visit my grandparents this weekend.",       jp:"こんしゅうまつ そふぼ を たずねる つもり です。" },
    { en:"The bridge was built more than a hundred years ago.",        jp:"その はし は 100ねん いじょう まえ に たてられました。" },
    { en:"She always helps her classmates with their homework.",       jp:"かのじょ は いつも クラスメイト の しゅくだい を てつだいます。" },
    { en:"There has been a lot of rain this month.",                   jp:"こんげつ は あめ が たくさん ふって います。" },
  ],
};
