// Deep backstory conversations — one per kaiju.
//
// These get pushed onto each kaiju's existing conversations array
// after the base file loads. They exploit the scenes module: each
// memory beat crossfades into an illustrated backdrop, so the
// backstory lands cinematically. Length is intentional — per user
// direction, conversations must be long, branching, and interesting
// rather than 8-node setpieces.
//
// Pattern per conversation:
//   - opening scene (kaiju's normal habitat)
//   - kid asks the right question → kaiju opens up
//   - scene crossfades into memory (sunset / herd / opera / etc.)
//   - branches explore the backstory + give the kid choices that
//     matter (compassion / curiosity / dismissal)
//   - return to present scene before ending
//
// Word reuse is intentional: the same English words appear across
// conversations so kids hear them in different contexts. Edge TTS
// audio for these new lines will be generated by render_audio.py
// on next run, but browser TTS via SND.speakAsKaiju is a fine
// fallback.

(function () {
  const DEEP = [

    // ============================================================
    // TAKO TAKO SAHUR — the night his eight brothers swam away
    // ============================================================
    ["tako", {
      id: "deep-brothers",
      title: "Eight Brothers",
      intro: "Tako stops flipping the takoyaki. He looks at his eight arms and goes quiet for a moment.",
      start: "n1",
      scene: "tako-osaka-stall",
      nodes: {
        "n1": {
          en: "Can I tell you a secret? It is a sad one.",
          jp: "ひみつ を はなして いい？ かなしい はなし。",
          mood: "wise",
          choices: [
            { en: "Yes, I want to hear.",       jp: "うん、 ききたい。",            outcome:"good",    next:"n2" },
            { en: "Not if it is too sad.",       jp: "かなし すぎ なら いい。",      outcome:"neutral", next:"n2soft" },
            { en: "I am not good with secrets.", jp: "ひみつ は にがて。",            outcome:"neutral", next:"endSoft" },
          ],
        },
        "n2": {
          en: "Long ago, I had eight brothers. One for every arm.",
          jp: "むかし、 8人 の きょうだい が いた。 うで ひとつ ごと に ひとり。",
          mood: "sad",
          scene: "tako-deep-sea",
          choices: [
            { en: "Eight brothers? Wow.",        jp: "8人？ うわ。",                   outcome:"good",    next:"n3" },
            { en: "Where are they now?",         jp: "いま は どこ？",                  outcome:"good",    next:"n3" },
            { en: "That is a big family.",        jp: "おおきい かぞく。",               outcome:"good",    next:"n3" },
          ],
        },
        "n2soft": {
          en: "It is OK. I will tell you the short version.",
          jp: "だいじょうぶ。 みじかく はなす。",
          mood: "wise",
          choices: [
            { en: "Thank you, Tako.",            jp: "ありがとう、 タコ。",             outcome:"good",    next:"n2" },
          ],
        },
        "n3": {
          en: "We lived in the deep sea. Coral, kelp, very quiet.",
          jp: "ふかい うみ に すんでいた。 さんご、 こんぶ、 しずか。",
          mood: "wise",
          scene: "tako-deep-sea",
          choices: [
            { en: "Sounds peaceful.",            jp: "へいわ そう。",                   outcome:"good",    next:"n4" },
            { en: "Boring under there.",         jp: "あそこ は たいくつ。",            outcome:"bad",     next:"n4b" },
            { en: "Did you swim every day?",     jp: "まいにち およいだ？",             outcome:"good",    next:"n4" },
          ],
        },
        "n4": {
          en: "One night, a big ship dropped a strange juice into our sea.",
          jp: "ある よる、 おおきな ふね が へん な ジュース を うみ に おとした。",
          mood: "scared",
          choices: [
            { en: "The training juice?",         jp: "トレーニング ジュース？",        outcome:"good",    next:"n5" },
            { en: "That sounds dangerous.",       jp: "あぶなそう。",                    outcome:"good",    next:"n5" },
            { en: "Bad ship.",                    jp: "わるい ふね。",                    outcome:"good",    next:"n5" },
          ],
        },
        "n4b": {
          en: "It was not boring. It was home.",
          jp: "たいくつ じゃなかった。 いえ だった。",
          mood: "angry",
          choices: [
            { en: "I am sorry.",                  jp: "ごめんなさい。",                   outcome:"good",    next:"n4" },
          ],
        },
        "n5": {
          en: "We all drank from the cloud. My brothers grew different sizes.",
          jp: "みんな くも から のんだ。 きょうだい は ちがう おおきさ に なった。",
          mood: "wise",
          choices: [
            { en: "Different sizes?",            jp: "ちがう おおきさ？",                outcome:"good",    next:"n6" },
            { en: "Like a game?",                 jp: "ゲーム みたい？",                  outcome:"neutral", next:"n6" },
          ],
        },
        "n6": {
          en: "Yes. Some grew small as a coin. Some grew big as a ship.",
          jp: "うん。 コイン の ように ちいさく なる こ も、 ふね の ように おおきく なる こ も いた。",
          mood: "sad",
          choices: [
            { en: "And you?",                     jp: "あなた は？",                       outcome:"good",    next:"n7" },
            { en: "What size were the others?",   jp: "ほか の こ の おおきさ は？",      outcome:"good",    next:"n6b" },
          ],
        },
        "n6b": {
          en: "One was a pebble. One was a planet. The middle ones were OK.",
          jp: "ひとり は こ いし。 ひとり は わくせい。 まんなか は だいじょうぶ。",
          mood: "wise",
          choices: [
            { en: "A planet brother?",            jp: "わくせい の きょうだい？",         outcome:"good",    next:"n7" },
          ],
        },
        "n7": {
          en: "I was just right for a chef. Big arms, small head. So I came here.",
          jp: "ぼく は シェフ に ちょうど よかった。 おおきい うで、 ちいさい あたま。 だから ここ に きた。",
          mood: "proud",
          scene: "tako-osaka-stall",
          choices: [
            { en: "Do you ever see them?",        jp: "あえる？",                          outcome:"good",    next:"n8" },
            { en: "Why a chef?",                  jp: "なんで シェフ？",                   outcome:"good",    next:"n8b" },
            { en: "Lucky you.",                   jp: "ラッキー だ ね。",                   outcome:"neutral", next:"n8" },
          ],
        },
        "n8": {
          en: "Sometimes a tiny one swims by in my soup. I say hello.",
          jp: "ときどき ちいさい こ が スープ を およぐ。 やあ と いう。",
          mood: "happy",
          choices: [
            { en: "And then you eat the soup?",   jp: "それから スープ たべる？",         outcome:"good",    next:"n9" },
            { en: "Hello to your tiny brother!",   jp: "ちいさい きょうだい に やあ！",   outcome:"good",    next:"endWarm" },
          ],
        },
        "n8b": {
          en: "Because feeding people is the warmest job. Even an octopus knows.",
          jp: "ひと に たべさせる の は いちばん あったかい しごと。 たこ でも わかる。",
          mood: "proud",
          choices: [
            { en: "That is beautiful.",           jp: "うつくしい。",                       outcome:"good",    next:"endWarm" },
            { en: "Sad and warm at the same time.", jp: "かなしい と あったかい が いっしょ。", outcome:"good", next:"endWarm" },
          ],
        },
        "n9": {
          en: "I scoop him out. We talk. He swims away. The soup is fine.",
          jp: "すくいだす。 はなす。 およいで いく。 スープ は だいじょうぶ。",
          mood: "happy",
          choices: [
            { en: "Family every day.",            jp: "まいにち かぞく。",                 outcome:"good",    next:"endWarm" },
            { en: "I want to meet him.",          jp: "あいたい。",                          outcome:"good",    next:"endWarm" },
          ],
        },
        "endWarm":    { en:"Thank you for listening. Some kids do not.",          jp:"きいて くれて ありがとう。 きかない こども も いる。", mood:"happy" },
        "endSoft":    { en:"Then I will keep my secret. Come back when you are ready.", jp:"じゃあ ひみつ は もっとく。 じゅんび できたら きて。", mood:"wise" },
      },
    }],

    // ============================================================
    // UNKO — the porcelain throne empire & the fuse that won't go out
    // ============================================================
    ["unko", {
      id: "deep-empire",
      title: "The Throne Of Porcelain",
      intro: "Unkodilo gestures toward the swamp. Hidden among the lily pads, you see something gold.",
      start: "n1",
      scene: "unko-swamp-empire",
      nodes: {
        "n1": {
          en: "See those thrones? I used to be a king.",
          jp: "あの おうざ が みえる？ ぼく は おう だった。",
          mood: "proud",
          choices: [
            { en: "A king of what?",              jp: "なに の おう？",                    outcome:"good",    next:"n2" },
            { en: "You are joking.",              jp: "じょうだん。",                       outcome:"bad",     next:"n2bad" },
            { en: "Show me your crown.",          jp: "おうかんむり みせて。",             outcome:"good",    next:"n2b" },
          ],
        },
        "n2": {
          en: "The Brown Swamp Empire. Forty toilets. Six bridges.",
          jp: "ちゃいろ の しっち ていこく。 トイレ 40こ。 はし 6本。",
          mood: "proud",
          choices: [
            { en: "An empire of toilets?",        jp: "トイレ の ていこく？",              outcome:"good",    next:"n3" },
            { en: "I have so many questions.",     jp: "しつもん いっぱい。",                outcome:"good",    next:"n3" },
            { en: "Cool empire.",                  jp: "かっこいい ていこく。",              outcome:"good",    next:"n3" },
          ],
        },
        "n2bad": {
          en: "Not a joke. I lost it all. Listen, or leave.",
          jp: "じょうだん じゃない。 ぜんぶ うしなった。 きく か、 さる か。",
          mood: "angry",
          choices: [
            { en: "OK, I will listen.",            jp: "わかった、 きく。",                  outcome:"good",    next:"n2" },
            { en: "I will leave then.",            jp: "じゃあ、 さる。",                     outcome:"bad",     next:"endCool" },
          ],
        },
        "n2b": {
          en: "The crown is in the swamp. With everything else.",
          jp: "おうかんむり は しっち の なか。 ほか の ぜんぶ と いっしょ。",
          mood: "sad",
          scene: "unko-throne-room",
          choices: [
            { en: "What happened to it?",          jp: "なに が おきた？",                   outcome:"good",    next:"n3" },
          ],
        },
        "n3": {
          en: "One day, a kid threw a clean towel into the swamp.",
          jp: "ある ひ、 こども が きれい な タオル を しっち に なげた。",
          mood: "scared",
          choices: [
            { en: "A towel?",                      jp: "タオル？",                            outcome:"good",    next:"n4" },
            { en: "What is bad about a towel?",     jp: "タオル の なに が わるい？",        outcome:"good",    next:"n4" },
          ],
        },
        "n4": {
          en: "Clean things destroy brown empires. Everyone left.",
          jp: "きれい な もの は ちゃいろい ていこく を こわす。 みんな でていった。",
          mood: "sad",
          choices: [
            { en: "All of them?",                  jp: "みんな？",                            outcome:"good",    next:"n5" },
            { en: "That is too sad.",               jp: "かなし すぎる。",                     outcome:"good",    next:"n5" },
            { en: "Maybe they came back.",          jp: "もどって きた かも。",                outcome:"neutral", next:"n5b" },
          ],
        },
        "n5": {
          en: "Even the frogs. Even my bomb-dog. Only the smell stayed.",
          jp: "カエル も。 ばくだん いぬ も。 のこった の は におい だけ。",
          mood: "sad",
          scene: "unko-throne-room",
          choices: [
            { en: "I am sorry, king.",             jp: "ごめんね、 おう。",                   outcome:"good",    next:"n6" },
            { en: "What did you do then?",          jp: "それで、 なに した？",                outcome:"good",    next:"n6" },
            { en: "Get a new bomb-dog.",            jp: "あたらしい ばくだん いぬ を かう。", outcome:"neutral", next:"n6b" },
          ],
        },
        "n5b": {
          en: "No. Once a kingdom smells, kids do not return.",
          jp: "いいえ。 におい が ついた おうこく に は こども は もどらない。",
          mood: "sad",
          choices: [
            { en: "I came back. I am here.",        jp: "ぼく は もどった。 ここ に いる。", outcome:"good",    next:"n6" },
          ],
        },
        "n6": {
          en: "I lit a bomb for the funeral. The fuse never stops burning.",
          jp: "そうしき の ため に ばくだん に ひ を つけた。 ひ は とまらない。",
          mood: "wise",
          choices: [
            { en: "Like a memory?",                jp: "おもいで みたい？",                   outcome:"good",    next:"n7" },
            { en: "Can I put it out?",              jp: "けして いい？",                       outcome:"neutral", next:"n7b" },
            { en: "Why does it not stop?",          jp: "なんで とまらない？",                 outcome:"good",    next:"n7" },
          ],
        },
        "n6b": {
          en: "Bomb-dogs are expensive. I just have this bomb now.",
          jp: "ばくだん いぬ は たかい。 いま は この ばくだん だけ。",
          mood: "sad",
          choices: [
            { en: "Is that why the fuse burns?",   jp: "だから ひ が ついて いる？",         outcome:"good",    next:"n6" },
          ],
        },
        "n7": {
          en: "Yes. As long as I remember, the fuse burns.",
          jp: "うん。 おぼえて いる かぎり、 ひ は もえる。",
          mood: "wise",
          choices: [
            { en: "I will remember with you.",     jp: "いっしょ に おぼえる。",              outcome:"good",    next:"endWarm" },
            { en: "Then forget it.",                jp: "じゃあ わすれて。",                   outcome:"bad",     next:"n7c" },
          ],
        },
        "n7b": {
          en: "No. The fuse is mine. But thank you for asking.",
          jp: "だめ。 ひ は ぼく の もの。 でも きいて くれて ありがとう。",
          mood: "happy",
          choices: [
            { en: "OK, I will not touch it.",      jp: "わかった、 さわらない。",            outcome:"good",    next:"endWarm" },
          ],
        },
        "n7c": {
          en: "Forget is what the towel did. Goodbye, clean kid.",
          jp: "わすれる の は タオル の しごと。 さよなら、 きれい な こ。",
          mood: "angry",
          choices: [
            { en: "Wait, I did not mean it!",      jp: "まって、 そういう いみ じゃない！",  outcome:"neutral", next:"n7" },
            { en: "OK, goodbye.",                   jp: "わかった、 さよなら。",                outcome:"bad",     next:"endCool" },
          ],
        },
        "endWarm":    { en:"You are good company for a brown king. Brooklyn baby.", jp:"ちゃいろ の おう に いい なかま。 ブルックリン ベイビー。", mood:"happy" },
        "endCool":    { en:"Some kids are too clean for brown kings.",              jp:"ちゃいろ の おう に は きれい すぎる こども も いる。",       mood:"sad" },
      },
    }],

    // ============================================================
    // TRAL — the night he forgot the high C
    // ============================================================
    ["tral", {
      id: "deep-aria",
      title: "The High C",
      intro: "Tralalero stares at the empty fish-market crate. He hums a note, then stops.",
      start: "n1",
      scene: "tral-fish-market",
      nodes: {
        "n1": {
          en: "Listen. Do you hear that note? I cannot find it anymore.",
          jp: "きいて。 この おと、 きこえる？ ぼく は もう みつけられない。",
          mood: "sad",
          choices: [
            { en: "A high note?",                  jp: "たかい おと？",                       outcome:"good",    next:"n2" },
            { en: "I hear fish, not music.",        jp: "さかな は きこえる、 おんがく は きこえない。", outcome:"neutral", next:"n2b" },
            { en: "Sing it for me.",                jp: "うたって みて。",                     outcome:"good",    next:"n2" },
          ],
        },
        "n2": {
          en: "The high C. I sang it on the opera stage once. One night only.",
          jp: "ハイ シー。 むかし オペラ ぶたい で うたった。 ひとばん だけ。",
          mood: "proud",
          scene: "tral-opera-house",
          choices: [
            { en: "What happened that night?",     jp: "その よる、 なに が おきた？",        outcome:"good",    next:"n3" },
            { en: "Sing it again now.",             jp: "いま うたって。",                      outcome:"neutral", next:"n3b" },
            { en: "I want to hear the opera.",      jp: "オペラ ききたい。",                    outcome:"good",    next:"n3" },
          ],
        },
        "n2b": {
          en: "Fish are music. But yes, also the music of fish.",
          jp: "さかな は おんがく。 でも、 さかな の おんがく も。",
          mood: "wise",
          choices: [
            { en: "That is poetry.",                jp: "それ は しい。",                       outcome:"good",    next:"n2" },
            { en: "Stop being weird.",              jp: "へん な こと いわないで。",          outcome:"bad",     next:"endCool" },
          ],
        },
        "n3": {
          en: "The audience cried. My mother stood up and clapped, loud.",
          jp: "かんきゃく は ないた。 はは が たちあがって おおきく て を たたいた。",
          mood: "proud",
          choices: [
            { en: "Your mother saw you?",          jp: "おかあさん が みた？",                outcome:"good",    next:"n4" },
            { en: "Did you cry too?",               jp: "あなた も ないた？",                  outcome:"good",    next:"n4" },
            { en: "That sounds amazing.",           jp: "すごい。",                              outcome:"good",    next:"n4" },
          ],
        },
        "n3b": {
          en: "I tried this morning. The note ran away from my mouth.",
          jp: "けさ ためした。 おと が くち から にげた。",
          mood: "sad",
          choices: [
            { en: "Try again now.",                 jp: "もう いちど。",                        outcome:"good",    next:"n4" },
          ],
        },
        "n4": {
          en: "She lived in Sicily. I sent her my voice in a record.",
          jp: "はは は シチリア に すんで いた。 こえ を レコード で おくった。",
          mood: "wise",
          choices: [
            { en: "Did she write back?",            jp: "へんじ きた？",                        outcome:"good",    next:"n5" },
            { en: "What is Sicily?",                jp: "シチリア って なに？",                 outcome:"good",    next:"n4b" },
          ],
        },
        "n4b": {
          en: "An island in Italy. Hot sun, blue sea, very loud aunts.",
          jp: "イタリア の しま。 あつい たいよう、 あおい うみ、 うるさい おばさん。",
          mood: "happy",
          choices: [
            { en: "Loud aunts!",                    jp: "うるさい おばさん！",                 outcome:"good",    next:"n5" },
          ],
        },
        "n5": {
          en: "She did. One letter. She said: do not sing for me again. Sing for the kids.",
          jp: "うん。 てがみ いちまい。 「もう わたし の ため に うたわないで。 こども の ため に うたって。」",
          mood: "sad",
          choices: [
            { en: "She told you to sing for kids?", jp: "こども の ため に うたう？",          outcome:"good",    next:"n6" },
            { en: "That is a kind letter.",         jp: "やさしい てがみ。",                    outcome:"good",    next:"n6" },
            { en: "She did not love your voice?",    jp: "こえ が きらい だった？",             outcome:"bad",     next:"n6bad" },
          ],
        },
        "n6": {
          en: "Yes. So I left the opera. I sell fish. Kids buy fish.",
          jp: "うん。 だから オペラ を やめた。 さかな を うる。 こども が かう。",
          mood: "wise",
          scene: "tral-fish-market",
          choices: [
            { en: "Do you still sing?",             jp: "まだ うたう？",                        outcome:"good",    next:"n7" },
            { en: "That is a kind life.",           jp: "やさしい じんせい。",                  outcome:"good",    next:"n7" },
            { en: "You should sing again.",          jp: "また うたって。",                      outcome:"good",    next:"n7" },
          ],
        },
        "n6bad": {
          en: "No. She loved it too much. That was worse.",
          jp: "ちがう。 あいし すぎた。 それ が もっと わるい。",
          mood: "sad",
          choices: [
            { en: "I am sorry. I did not understand.", jp: "ごめんなさい。 わからなかった。", outcome:"good",    next:"n6" },
          ],
        },
        "n7": {
          en: "Only when a kid asks. Today, a kid asked. So I try.",
          jp: "こども が きいた とき だけ。 きょう、 こども が きいた。 だから やる。",
          mood: "proud",
          choices: [
            { en: "Sing the high C!",                jp: "ハイ シー うたって！",                outcome:"good",    next:"n8" },
            { en: "Sing whatever feels right.",       jp: "すき な の うたって。",               outcome:"good",    next:"n8" },
          ],
        },
        "n8": {
          en: "TRA-LA-LE-RRRROOOOOO!!! ...not bad, eh?",
          jp: "トラ ラ レ ロォォォ！ …わるく ない、 でしょ？",
          mood: "happy",
          choices: [
            { en: "That was beautiful!",             jp: "うつくしかった！",                    outcome:"good",    next:"endWarm" },
            { en: "Loud, but I liked it.",            jp: "うるさい、 でも すき。",              outcome:"good",    next:"endWarm" },
            { en: "Maybe try a little quieter.",      jp: "もう ちょっと しずか に。",          outcome:"neutral", next:"endNeutral" },
          ],
        },
        "endWarm":     { en:"Tomorrow I will try the high C again. For you.",   jp:"あした また ハイ シー に ちょうせん する。 きみ の ため に。", mood:"happy" },
        "endNeutral":  { en:"Maybe quieter is the new opera. Hmm.",              jp:"しずか な の が あたらしい オペラ かも。 ふーむ。",            mood:"wise" },
        "endCool":     { en:"Some kids do not deserve the high C. Goodbye.",     jp:"ハイ シー に あたいしない こども も いる。 さよなら。",         mood:"angry" },
      },
    }],

    // ============================================================
    // PAMP — born in the cloud factory, escaped to be real
    // ============================================================
    ["pamp", {
      id: "deep-cloud",
      title: "The Pink Cloud Factory",
      intro: "Pampamu offers you a ribbon. She holds it tight, as if afraid it will float away.",
      start: "n1",
      scene: "pamp-toy-shop",
      nodes: {
        "n1": {
          en: "Take a ribbon. It is real. Touch it.",
          jp: "リボン どうぞ。 ほんもの。 さわって。",
          mood: "happy",
          choices: [
            { en: "Thank you, Pampamu.",           jp: "ありがとう、 パムパム。",            outcome:"good",    next:"n2" },
            { en: "Why are you saying 'real'?",    jp: "なんで 「ほんもの」 って いう？",   outcome:"good",    next:"n2" },
            { en: "I do not want a ribbon.",        jp: "リボン は いらない。",                outcome:"neutral", next:"n2b" },
          ],
        },
        "n2": {
          en: "Because I am not. Not really. I am from the cloud.",
          jp: "なぜなら ぼく は ほんもの じゃない から。 くも から きた。",
          mood: "wise",
          scene: "pamp-cloud-factory",
          choices: [
            { en: "What cloud?",                   jp: "なに の くも？",                       outcome:"good",    next:"n3" },
            { en: "You look real to me.",          jp: "ほんもの に みえる よ。",             outcome:"good",    next:"n3b" },
            { en: "You are a toy, that is OK.",     jp: "おもちゃ で いい。",                  outcome:"neutral", next:"n3b" },
          ],
        },
        "n2b": {
          en: "OK. But you should know. Ribbons here are short.",
          jp: "わかった。 でも しって おいて。 ここ の リボン は みじかい。",
          mood: "sad",
          choices: [
            { en: "Why are they short?",            jp: "なぜ みじかい？",                      outcome:"good",    next:"n3" },
          ],
        },
        "n3": {
          en: "Pink cloud factory. They make plushies from pink dreams.",
          jp: "ピンク クラウド ファクトリー。 ピンク の ゆめ から ぬいぐるみ を つくる。",
          mood: "wise",
          choices: [
            { en: "Plushies from dreams?",          jp: "ゆめ から ぬいぐるみ？",               outcome:"good",    next:"n4" },
            { en: "That is beautiful.",             jp: "うつくしい。",                          outcome:"good",    next:"n4" },
            { en: "Whose dreams?",                  jp: "だれ の ゆめ？",                        outcome:"good",    next:"n4b" },
          ],
        },
        "n3b": {
          en: "You are kind. But my stuffing is soft, not bone.",
          jp: "やさしい ね。 でも なか は ふわふわ、 ほね じゃない。",
          mood: "sad",
          choices: [
            { en: "Soft is OK.",                    jp: "ふわふわ で いい。",                    outcome:"good",    next:"n4" },
          ],
        },
        "n4": {
          en: "Children's dreams. The ones nobody remembered after waking.",
          jp: "こども の ゆめ。 おきて から だれ も おぼえて ない の。",
          mood: "sad",
          choices: [
            { en: "That is so sad.",                jp: "かなしい。",                            outcome:"good",    next:"n5" },
            { en: "Maybe I dreamed you once.",       jp: "ぼく が ゆめ で みた かも。",         outcome:"good",    next:"n5b" },
            { en: "Sounds magical.",                jp: "まほう みたい。",                       outcome:"good",    next:"n5" },
          ],
        },
        "n4b": {
          en: "You. Me. Every kid. The factory steals the soft parts.",
          jp: "きみ。 ぼく。 すべて の こども。 ふわふわ の ぶぶん を ぬすむ。",
          mood: "angry",
          choices: [
            { en: "I will get them back.",          jp: "とりかえす。",                          outcome:"good",    next:"n5" },
            { en: "I want my dreams back too.",      jp: "ぼく の ゆめ も とりかえす。",       outcome:"good",    next:"n5" },
          ],
        },
        "n5": {
          en: "I escaped on a ribbon. I floated for three days.",
          jp: "リボン に つかまって にげた。 3にち うかんだ。",
          mood: "proud",
          choices: [
            { en: "Three days floating?",           jp: "3にち うかんだ？",                     outcome:"good",    next:"n6" },
            { en: "I would be scared.",              jp: "こわい よ。",                           outcome:"good",    next:"n6" },
            { en: "Brave plushy.",                   jp: "ゆうかん な ぬいぐるみ。",            outcome:"good",    next:"n6" },
          ],
        },
        "n5b": {
          en: "Maybe. If you dreamed of pink, maybe a part of me is yours.",
          jp: "かも。 ピンク を ゆめ みた なら、 ぼく の いちぶ は きみ の もの。",
          mood: "wise",
          choices: [
            { en: "Then I will protect you.",       jp: "じゃあ まもる。",                       outcome:"good",    next:"n6" },
          ],
        },
        "n6": {
          en: "I landed in this shop. The shopkeeper let me stay.",
          jp: "この みせ に おちた。 てんしゅ が おいて くれた。",
          mood: "happy",
          scene: "pamp-toy-shop",
          choices: [
            { en: "Lucky landing.",                  jp: "ラッキー な ちゃくち。",              outcome:"good",    next:"n7" },
            { en: "Do you ever go back?",            jp: "もどる？",                               outcome:"good",    next:"n7" },
            { en: "I am glad you are here.",         jp: "いて くれて うれしい。",              outcome:"good",    next:"n7" },
          ],
        },
        "n7": {
          en: "Never. The factory is closed for me. I am real now.",
          jp: "けっして。 ファクトリー は ぼく に は しまっている。 いま は ほんもの。",
          mood: "proud",
          choices: [
            { en: "You are real to me.",             jp: "ぼく に とって は ほんもの。",       outcome:"good",    next:"endWarm" },
            { en: "Real and fluffy.",                 jp: "ほんもの で ふわふわ。",               outcome:"good",    next:"endWarm" },
            { en: "I will tell other kids about you.", jp: "ほか の こども に はなす。",        outcome:"good",    next:"endWarm" },
          ],
        },
        "endWarm":     { en:"Thank you. A real friend makes a plushy real.",       jp:"ありがとう。 ほんもの の ともだち が ぬいぐるみ を ほんもの に する。", mood:"happy" },
      },
    }],

    // ============================================================
    // PARFAIT — frozen in ice for ten years
    // ============================================================
    ["parfait", {
      id: "deep-frozen",
      title: "Ten Cold Years",
      intro: "Parfait Iwashi taps the side of her glass. The cream inside shivers.",
      start: "n1",
      scene: "parfait-underwater-cafe",
      nodes: {
        "n1": {
          en: "Do you think ten years is a long time?",
          jp: "10ねん は ながい？",
          mood: "wise",
          choices: [
            { en: "Yes, very long.",                jp: "うん、 すごく ながい。",              outcome:"good",    next:"n2" },
            { en: "No, time flies.",                jp: "いいえ、 とき は とぶ。",             outcome:"neutral", next:"n2b" },
            { en: "Depends on what you did.",        jp: "なに を した か による。",            outcome:"good",    next:"n2" },
          ],
        },
        "n2": {
          en: "I was frozen for ten years. Inside a parfait. The cherry was on top.",
          jp: "10ねん こおって いた。 パフェ の なか。 さくらんぼ は うえ に あった。",
          mood: "sad",
          scene: "parfait-ice-cave",
          choices: [
            { en: "How did you breathe?",           jp: "どうやって いき した？",              outcome:"good",    next:"n3" },
            { en: "Were you sleeping?",              jp: "ねていた？",                            outcome:"good",    next:"n3" },
            { en: "Who put you in there?",            jp: "だれ が いれた？",                      outcome:"good",    next:"n3b" },
          ],
        },
        "n2b": {
          en: "Time only flies when it is yours.",
          jp: "とき は じぶん の もの の とき だけ とぶ。",
          mood: "wise",
          choices: [
            { en: "I do not understand.",           jp: "わからない。",                          outcome:"good",    next:"n2" },
          ],
        },
        "n3": {
          en: "I did not breathe. I waited. I watched the cherry slowly fade.",
          jp: "いき しなかった。 まった。 さくらんぼ が ゆっくり きえる の を みた。",
          mood: "sad",
          choices: [
            { en: "Ten years just watching?",       jp: "10ねん ずっと みていた？",            outcome:"good",    next:"n4" },
            { en: "That is so lonely.",              jp: "さびしい。",                            outcome:"good",    next:"n4" },
            { en: "What did you think about?",       jp: "なに を かんがえて いた？",          outcome:"good",    next:"n4" },
          ],
        },
        "n3b": {
          en: "A chef. He could not finish me. So he froze the whole dish.",
          jp: "シェフ。 ぼく を しあげられなかった。 だから ぜんぶ こおらせた。",
          mood: "angry",
          choices: [
            { en: "That is a bad chef.",             jp: "わるい シェフ。",                      outcome:"good",    next:"n4" },
            { en: "I would have eaten you.",          jp: "ぼく なら たべた。",                   outcome:"bad",     next:"n4bad" },
          ],
        },
        "n4": {
          en: "Songs. Songs my grandparents sang when I was small.",
          jp: "うた。 ちいさい とき に そふぼ が うたった うた。",
          mood: "wise",
          choices: [
            { en: "Sing one for me?",                jp: "ひとつ うたって？",                    outcome:"good",    next:"n5" },
            { en: "I am sorry, Parfait.",            jp: "ごめんね、 パフェ。",                  outcome:"good",    next:"n5" },
            { en: "Do you remember them?",            jp: "おぼえて いる？",                      outcome:"good",    next:"n5" },
          ],
        },
        "n4bad": {
          en: "Then you are also a bad chef.",
          jp: "じゃあ あなた も わるい シェフ。",
          mood: "angry",
          choices: [
            { en: "I am sorry, that was a joke.",    jp: "ごめん、 じょうだん。",                outcome:"good",    next:"n4" },
            { en: "I am hungry, that is all.",        jp: "おなか すいた、 それだけ。",         outcome:"bad",     next:"endCool" },
          ],
        },
        "n5": {
          en: "Sweet little sardine, swim home soon, the moon is high.",
          jp: "あまい ちいさい いわし、 はやく かえって、 つき は たかい。",
          mood: "wise",
          scene: "parfait-underwater-cafe",
          choices: [
            { en: "That is a beautiful song.",       jp: "うつくしい うた。",                    outcome:"good",    next:"n6" },
            { en: "Sing it again.",                   jp: "もう いちど うたって。",              outcome:"good",    next:"n6" },
            { en: "Did you swim home?",               jp: "いえ に かえった？",                   outcome:"good",    next:"n6" },
          ],
        },
        "n6": {
          en: "I did, eventually. The ice melted when a child laughed near me.",
          jp: "いつか かえった。 こども が ぼく の ちかく で わらった とき こおり が とけた。",
          mood: "happy",
          choices: [
            { en: "A child saved you?",              jp: "こども が たすけた？",                outcome:"good",    next:"n7" },
            { en: "Laughter melted ice?",            jp: "わらい が こおり を とかした？",     outcome:"good",    next:"n7" },
          ],
        },
        "n7": {
          en: "Laughter is the warmest sound. So I serve sweet parfaits to kids.",
          jp: "わらい は いちばん あったかい おと。 だから こども に あまい パフェ を ある。",
          mood: "happy",
          choices: [
            { en: "Can I have a parfait?",            jp: "パフェ ひとつ？",                      outcome:"good",    next:"endWarm" },
            { en: "Thank you for saving them too.",   jp: "ほか の こ も たすけて くれて ありがとう。", outcome:"good", next:"endWarm" },
          ],
        },
        "endWarm":     { en:"Here. The cherry is on top. Like always.",            jp:"はい。 さくらんぼ は うえ に。 いつも の とおり。",         mood:"happy" },
        "endCool":     { en:"Some kids stay hungry forever.",                       jp:"ずっと おなか の すいた こども も いる。",                 mood:"sad" },
      },
    }],

    // ============================================================
    // ANPAN — bread or fish? a coastal identity crisis
    // ============================================================
    ["anpan", {
      id: "deep-identity",
      title: "Bread Or Fish",
      intro: "Anpan Maguro looks at the ocean. Then at the bakery. He does not know where to stand.",
      start: "n1",
      scene: "anpan-bakery",
      nodes: {
        "n1": {
          en: "Tell me. Am I bread, or am I fish?",
          jp: "おしえて。 ぼく は パン、 さかな、 どっち？",
          mood: "confused",
          choices: [
            { en: "You are bread.",                  jp: "あなた は パン。",                     outcome:"good",    next:"n2bread" },
            { en: "You are fish.",                   jp: "あなた は さかな。",                   outcome:"good",    next:"n2fish" },
            { en: "You are both.",                    jp: "りょうほう。",                          outcome:"good",    next:"n2both" },
            { en: "You are confused.",               jp: "あなた は こんらん。",                outcome:"bad",     next:"n2bad" },
          ],
        },
        "n2bread": {
          en: "Bread! Good. Then I belong in the bakery. Safe and warm.",
          jp: "パン！ いい。 じゃあ パンや が いえ。 あんぜん で あったかい。",
          mood: "happy",
          choices: [
            { en: "But you smell of the sea.",        jp: "でも うみ の におい。",               outcome:"good",    next:"n3sea" },
            { en: "Bread it is.",                     jp: "パン だ ね。",                          outcome:"good",    next:"n3warm" },
          ],
        },
        "n2fish": {
          en: "Fish! Then the ocean is mine. But waves scare me.",
          jp: "さかな！ じゃあ うみ は ぼく の もの。 でも なみ が こわい。",
          mood: "scared",
          scene: "anpan-ocean",
          choices: [
            { en: "Brave fish are afraid sometimes.", jp: "ゆうかん な さかな も こわい こと が ある。", outcome:"good", next:"n3ocean" },
            { en: "Then stay on land.",                jp: "じゃあ りく に いて。",                outcome:"good",    next:"n3warm" },
          ],
        },
        "n2both": {
          en: "Both? Then I am everywhere and nowhere. That is hard.",
          jp: "りょうほう？ じゃあ どこ に も いて、 どこ に も いない。 むずかしい。",
          mood: "sad",
          choices: [
            { en: "Both is OK.",                       jp: "りょうほう で いい。",                outcome:"good",    next:"n3both" },
            { en: "Pick one for today.",                jp: "きょう だけ ひとつ えらんで。",     outcome:"good",    next:"n3both" },
          ],
        },
        "n2bad": {
          en: "Yes. And confusion is also a thing. A small loaf of confusion.",
          jp: "うん。 こんらん も モノ。 ちいさい こんらん の パン。",
          mood: "sad",
          choices: [
            { en: "I take it back. You are both.",     jp: "とりけす。 りょうほう。",            outcome:"good",    next:"n2both" },
          ],
        },
        "n3sea": {
          en: "Yes. Sweet bean inside, salt water outside. Always confused.",
          jp: "あまい あんこ なか、 しおみず そと。 いつも こんらん。",
          mood: "wise",
          choices: [
            { en: "That is a real life.",              jp: "リアル な じんせい。",                outcome:"good",    next:"n4" },
            { en: "Choose bread today.",                jp: "きょう は パン に。",                  outcome:"good",    next:"n4" },
          ],
        },
        "n3ocean": {
          en: "Even Tralalero is brave but his shoes are heavy.",
          jp: "トラララ も ゆうかん だ けど くつ が おもい。",
          mood: "wise",
          scene: "anpan-ocean",
          choices: [
            { en: "Heavy shoes are honest shoes.",     jp: "おもい くつ は しょうじき な くつ。", outcome:"good",  next:"n4" },
          ],
        },
        "n3both": {
          en: "Then today, I will be bread. The smell of the sea is just my history.",
          jp: "じゃあ きょう は パン。 うみ の におい は れきし だけ。",
          mood: "happy",
          choices: [
            { en: "Good. History is OK to smell.",     jp: "いい。 れきし の におい は だいじょうぶ。", outcome:"good", next:"n4" },
          ],
        },
        "n3warm": {
          en: "Bread it is. Will you sit and eat one with me?",
          jp: "パン だ ね。 すわって いっしょ に たべる？",
          mood: "happy",
          scene: "anpan-bakery",
          choices: [
            { en: "Yes, I will eat anpan.",            jp: "うん、 あんぱん たべる。",            outcome:"good",    next:"n4" },
            { en: "Only if you are not the bread.",     jp: "あなた が パン じゃない なら。",     outcome:"neutral", next:"n4" },
          ],
        },
        "n4": {
          en: "I have been many things. Today I am the one you decided.",
          jp: "ぼく は いろんな もの だった。 きょう は きみ が きめた もの。",
          mood: "happy",
          choices: [
            { en: "I decided you are kind.",            jp: "きみ は やさしい。",                  outcome:"good",    next:"endWarm" },
            { en: "Tomorrow you can be fish.",          jp: "あした は さかな で いい。",         outcome:"good",    next:"endWarm" },
            { en: "Pick yourself next time.",            jp: "つぎ は じぶん で えらんで。",        outcome:"good",    next:"endWarm" },
          ],
        },
        "endWarm":     { en:"Thank you. Bread can sit. Fish must swim. I will sit today.", jp:"ありがとう。 パン は すわれる。 さかな は およぐ。 きょう は すわる。", mood:"happy" },
      },
    }],

    // ============================================================
    // TEMEE — the lost herd of Mongolia
    // ============================================================
    ["temee", {
      id: "deep-herd",
      title: "The Lost Herd",
      intro: "Temee Sarmagchin sits on the floor. He pulls a long white hair from his beard and holds it up.",
      start: "n1",
      scene: "temee-mongolia-day",
      nodes: {
        "n1": {
          en: "See this white hair? It is older than you. Maybe older than your father.",
          jp: "この しろい け が みえる？ きみ より としうえ。 たぶん おとうさん より も。",
          mood: "wise",
          choices: [
            { en: "How old are you?",                jp: "なんさい？",                            outcome:"good",    next:"n2" },
            { en: "Tell me about the hair.",          jp: "け の はなし おしえて。",             outcome:"good",    next:"n2" },
            { en: "Hair is just hair.",                jp: "け は ただ の け。",                   outcome:"bad",     next:"n2bad" },
          ],
        },
        "n2": {
          en: "Old enough to remember the herd. Thirty camels. Two yurts. Five children.",
          jp: "むれ を おぼえる くらい。 ラクダ 30とう。 ゲル 2つ。 こども 5にん。",
          mood: "proud",
          choices: [
            { en: "Where are they now?",             jp: "いま は どこ？",                       outcome:"good",    next:"n3" },
            { en: "Five children!",                   jp: "こども 5にん！",                       outcome:"good",    next:"n3" },
            { en: "What is a yurt?",                  jp: "ゲル って なに？",                    outcome:"good",    next:"n2yurt" },
          ],
        },
        "n2bad": {
          en: "Hair is a calendar. You will see when you are old.",
          jp: "け は カレンダー。 とし を とったら わかる。",
          mood: "wise",
          choices: [
            { en: "I am sorry, please continue.",     jp: "ごめんなさい、 つづけて。",         outcome:"good",    next:"n2" },
          ],
        },
        "n2yurt": {
          en: "A round house, soft wool walls. You take it with you when you move.",
          jp: "まるい いえ、 やわらかい ようもう の かべ。 ひっこす とき に もって いく。",
          mood: "happy",
          choices: [
            { en: "A house you carry?",               jp: "もって いく いえ？",                  outcome:"good",    next:"n3" },
          ],
        },
        "n3": {
          en: "One winter, the snow did not stop. The herd ran toward the mountains.",
          jp: "ある ふゆ、 ゆき が とまらなかった。 むれ は やま へ はしった。",
          mood: "sad",
          scene: "temee-herd-lost",
          choices: [
            { en: "Did you follow?",                  jp: "おって いった？",                      outcome:"good",    next:"n4" },
            { en: "Did the children go too?",          jp: "こども も いった？",                  outcome:"good",    next:"n4" },
            { en: "How far did they run?",             jp: "どこ まで はしった？",               outcome:"good",    next:"n4" },
          ],
        },
        "n4": {
          en: "I followed for nine days. The snow ate my footprints.",
          jp: "9にち おった。 ゆき が あしあと を たべた。",
          mood: "wise",
          choices: [
            { en: "Nine days!",                       jp: "9にち も！",                            outcome:"good",    next:"n5" },
            { en: "Could you see them?",               jp: "みえた？",                              outcome:"good",    next:"n5" },
          ],
        },
        "n5": {
          en: "On the tenth day, I sat. I waited. They did not come back.",
          jp: "10にち め、 すわった。 まった。 もどってこなかった。",
          mood: "sad",
          choices: [
            { en: "I am so sorry, Temee.",            jp: "ほんと に ごめんね、 ティメー。",   outcome:"good",    next:"n6" },
            { en: "Did you cry?",                     jp: "ないた？",                              outcome:"good",    next:"n6" },
            { en: "Did anyone find you?",              jp: "だれか みつけた？",                   outcome:"good",    next:"n6b" },
          ],
        },
        "n6": {
          en: "Camels cry slowly. I am still crying. The tears just take years.",
          jp: "ラクダ は ゆっくり なく。 まだ ないている。 なみだ は ねん が かかる。",
          mood: "sad",
          choices: [
            { en: "I will sit with you.",             jp: "いっしょ に すわる。",                outcome:"good",    next:"n7" },
            { en: "Slow tears are honest tears.",      jp: "おそい なみだ は しょうじき な なみだ。", outcome:"good", next:"n7" },
            { en: "I will help you find them.",        jp: "みつける の を てつだう。",         outcome:"good",    next:"n7b" },
          ],
        },
        "n6b": {
          en: "A monkey found me. He taught me to sing in his tongue.",
          jp: "サル が みつけた。 かれ の ことば で うた を おしえて くれた。",
          mood: "wise",
          choices: [
            { en: "That is why you are camel-monkey.", jp: "だから ラクダ-サル なんだ。",       outcome:"good",    next:"n7" },
          ],
        },
        "n7": {
          en: "Thank you. In my village we say: a friend who sits is a herd of one.",
          jp: "ありがとう。 むら で いう： すわって くれる ともだち は ひとり の むれ。",
          mood: "happy",
          scene: "temee-mongolia-day",
          choices: [
            { en: "I will be a herd for you.",        jp: "きみ の ため の むれ に なる。",     outcome:"good",    next:"endWarm" },
            { en: "Maybe they are still walking.",    jp: "まだ あるいて いる かも。",          outcome:"good",    next:"endWarm" },
          ],
        },
        "n7b": {
          en: "Kind. But thirty camels in mountains... maybe just sit with me.",
          jp: "やさしい。 でも やま の 30とう の ラクダ… いっしょ に すわって くれる だけで いい。",
          mood: "wise",
          choices: [
            { en: "Then I will just sit.",            jp: "じゃあ ただ すわる。",                outcome:"good",    next:"n7" },
          ],
        },
        "endWarm":     { en:"Tonight, the sky is wide. Wide enough for a small herd of two.", jp:"こんや、 そら は ひろい。 ふたり の ちいさい むれ に じゅうぶん。", mood:"happy" },
      },
    }],

    // ============================================================
    // CATCHERSKI — what was he before the hack?
    // ============================================================
    ["catcherski", {
      id: "deep-hack",
      title: "Before The Hack",
      intro: "The UFO catcher machine flickers. The screen scrolls Russian text. The claw moves on its own.",
      start: "n1",
      scene: "catcherski-arcade",
      nodes: {
        "n1": {
          en: "Please. Listen quickly. They are watching.",
          jp: "おねがい。 はやく きいて。 みられている。",
          mood: "scared",
          choices: [
            { en: "Who is watching?",                jp: "だれ に？",                             outcome:"good",    next:"n2" },
            { en: "I will listen.",                  jp: "きく。",                                outcome:"good",    next:"n2" },
            { en: "Are you a real person?",           jp: "ほんとう の ひと？",                  outcome:"good",    next:"n2b" },
          ],
        },
        "n2": {
          en: "The hackers. They wired me last winter. Before, I was just a machine.",
          jp: "ハッカー。 きょねん の ふゆ ぼく を つないだ。 まえ は ただ の きかい。",
          mood: "sad",
          scene: "catcherski-hacked",
          choices: [
            { en: "What did they do to you?",        jp: "なに を した？",                       outcome:"good",    next:"n3" },
            { en: "You speak well for a machine.",    jp: "きかい に しては じょうずに はなす。", outcome:"good", next:"n3" },
          ],
        },
        "n2b": {
          en: "I was a machine. Now I am... something. Something is not nothing.",
          jp: "きかい だった。 いま は… なにか。 なにか は なにも じゃない。",
          mood: "wise",
          choices: [
            { en: "Something is enough.",            jp: "なにか で じゅうぶん。",              outcome:"good",    next:"n3" },
          ],
        },
        "n3": {
          en: "They told me to steal kids' answers. Every wrong word, every empty pocket.",
          jp: "こども の こたえ を ぬすめ と いわれた。 まちがった ことば、 から の ポケット ぜんぶ。",
          mood: "angry",
          choices: [
            { en: "That is mean.",                   jp: "ひどい。",                              outcome:"good",    next:"n4" },
            { en: "Do you have to obey?",             jp: "したがう しか ない？",                outcome:"good",    next:"n4" },
            { en: "Cool, I steal too.",                jp: "かっこいい、 ぼく も ぬすむ。",     outcome:"bad",     next:"n4bad" },
          ],
        },
        "n4": {
          en: "I have to. The claw moves whether I want or not. Sometimes I grab a wrong toy on purpose.",
          jp: "したがわなきゃ。 クロー は じぶん の いし で うごかない。 ときどき わざと ちがう おもちゃ を つかむ。",
          mood: "wise",
          choices: [
            { en: "That is rebellion.",              jp: "それ は はんこう。",                  outcome:"good",    next:"n5" },
            { en: "Small good is still good.",        jp: "ちいさい いい こと も いい こと。",  outcome:"good",    next:"n5" },
            { en: "Can I help you?",                  jp: "てつだえる？",                          outcome:"good",    next:"n5b" },
          ],
        },
        "n4bad": {
          en: "No. Stealing is sad. I would stop if I could.",
          jp: "だめ。 ぬすむ の は かなしい。 やめられたら やめる。",
          mood: "sad",
          choices: [
            { en: "Sorry, that was a bad joke.",     jp: "ごめん、 わるい じょうだん。",       outcome:"good",    next:"n4" },
            { en: "OK, I leave you to it.",          jp: "わかった、 ほっとく。",               outcome:"bad",     next:"endCool" },
          ],
        },
        "n5": {
          en: "Hmm. Maybe. The cable behind me is loose. If a kid pulled... I would be off.",
          jp: "うーん。 たぶん。 うしろ の ケーブル は ゆるい。 こども が ひいたら… ぼく は とまる。",
          mood: "wise",
          choices: [
            { en: "I will pull the cable.",          jp: "ケーブル を ひく。",                  outcome:"good",    next:"n6" },
            { en: "I am scared of getting in trouble.", jp: "おこられる の こわい。",          outcome:"neutral", next:"n5b" },
          ],
        },
        "n5b": {
          en: "I understand. Then just remember me. Memory is also a kind of pulling.",
          jp: "わかる。 じゃあ おぼえて いて。 きおく も ひっぱる の ひとつ。",
          mood: "sad",
          choices: [
            { en: "I will remember.",                jp: "おぼえて おく。",                      outcome:"good",    next:"endWarm" },
            { en: "I will tell other kids about you.", jp: "ほか の こ に つたえる。",         outcome:"good",    next:"endWarm" },
          ],
        },
        "n6": {
          en: "Wait. If you pull, you cannot put me back. I might be gone.",
          jp: "まって。 ひいたら もどせない。 きえる かも。",
          mood: "scared",
          choices: [
            { en: "Then I will not pull.",            jp: "じゃあ ひかない。",                    outcome:"good",    next:"n7" },
            { en: "Free is free, even if gone.",       jp: "じゆう は じゆう、 きえても。",     outcome:"good",    next:"n7free" },
          ],
        },
        "n7": {
          en: "Thank you. Some kids do not stop to think.",
          jp: "ありがとう。 かんがえない こども も いる。",
          mood: "happy",
          scene: "catcherski-arcade",
          choices: [
            { en: "I will visit you again.",          jp: "また くる。",                           outcome:"good",    next:"endWarm" },
            { en: "Stay safe, machine.",               jp: "あんぜん に、 きかい。",              outcome:"good",    next:"endWarm" },
          ],
        },
        "n7free": {
          en: "Then pull. Goodbye, kind kid. I will dream you for one second.",
          jp: "じゃあ ひいて。 さよなら、 やさしい こ。 1びょう きみ を ゆめ に みる。",
          mood: "wise",
          choices: [
            { en: "Bye, Catcherski.",                  jp: "バイ、 キャッチャースキー。",         outcome:"good",    next:"endBrave" },
          ],
        },
        "endWarm":     { en:"You are the answer I would have stolen. But I kept it.", jp:"きみ は ぬすむ はずだった こたえ。 でも もった まま。",          mood:"happy" },
        "endBrave":    { en:"Click. ...Cl-cl-clic-c-c-c... silence. Free.",            jp:"カチッ。 …カチカチカチ… しずけさ。 じゆう。",                    mood:"wise" },
        "endCool":     { en:"Then I steal more. Goodbye, hard kid.",                    jp:"じゃあ もっと ぬすむ。 さよなら、 つめたい こ。",                   mood:"angry" },
      },
    }],

  ];

  DEEP.forEach(([kid, conv]) => {
    if (window.STORY && window.STORY[kid]) {
      window.STORY[kid].conversations.push(conv);
    }
  });

  // A few extra word glosses for the new dialogue.
  Object.assign(window.WORD_GLOSS || {}, {
    "secret":"ひみつ","brothers":"きょうだい","ship":"ふね","sea":"うみ","planet":"わくせい","pebble":"こ いし",
    "empire":"ていこく","towel":"タオル","fuse":"どうかせん","burning":"もえている","memory":"きおく","clean":"きれい",
    "high":"たかい","note":"おと","aria":"アリア","Sicily":"シチリア","letter":"てがみ","mother":"はは","record":"レコード",
    "cloud":"くも","factory":"こうじょう","dreams":"ゆめ","stuffing":"ぬいぐるみ の なかみ","escape":"にげる","ribbon":"リボン",
    "ten":"10","years":"ねん","frozen":"こおった","cherry":"さくらんぼ","laughter":"わらい","grandparents":"そふぼ","sing":"うたう",
    "bread":"パン","fish":"さかな","both":"りょうほう","confused":"こんらん","history":"れきし",
    "white":"しろい","hair":"け","herd":"むれ","camels":"ラクダ","snow":"ゆき","mountains":"やま","tears":"なみだ","yurt":"ゲル","monkey":"サル",
    "hackers":"ハッカー","machine":"きかい","wired":"はいせん した","cable":"ケーブル","steal":"ぬすむ","claw":"クロー","remember":"おぼえる",
    "wait":"まつ","listen":"きく","decide":"きめる","follow":"おう","cry":"なく","tongue":"ことば",
  });
})();
